--12345
--45678-
--建立目錄
--product是分工，依照自己的分工建立自己的資料夾
--ca102g4_pics 勿改
CREATE OR REPLACE DIRECTORY image_product_dir AS 'c:\ca102g4_pics\product';
CREATE OR REPLACE DIRECTORY image_ad_dir AS 'c:\ca102g4_pics\ad';
CREATE OR REPLACE DIRECTORY image_blog_dir AS 'c:\ca102g4_pics\blog';
CREATE OR REPLACE DIRECTORY IMAGE_ATTRACTIONS_DIR AS 'C:\ca102g4_pics\attractions';
CREATE OR REPLACE DIRECTORY image_grp_dir AS 'C:\ca102g4_pics\grp';
CREATE OR REPLACE DIRECTORY image_member_dir AS 'C:\ca102g4_pics\member';
CREATE OR REPLACE DIRECTORY image_photo_wall_dir AS 'C:\ca102g4_pics\photo_wall';

--建立bfile 轉 blob 函式

create or replace FUNCTION bfile_to_blob
 (p_bfile     IN BFILE)
 RETURN           BLOB
 AS v_src_file      BFILE := p_bfile;
V_AMOUNT        INTEGER;
v_dest_lob      BLOB;
BEGIN
DBMS_LOB.OPEN (v_src_file, DBMS_LOB.LOB_READONLY);
v_amount := DBMS_LOB.GETLENGTH (v_src_file);
DBMS_LOB.CREATETEMPORARY (v_dest_lob, FALSE, DBMS_LOB.CALL);
DBMS_LOB.LOADFROMFILE (v_dest_lob, v_src_file, v_amount);
DBMS_LOB.CLOSE (v_src_file);
RETURN v_dest_lob;
END bfile_to_blob;
/


DROP TABLE  NEWS CASCADE CONSTRAINTS;
CREATE TABLE  NEWS (
NEWS_ID VARCHAR2(20) NOT NULL,
NEWS_NAME VARCHAR2(200) NOT NULL,
NEWS_DATE DATE NOT NULL,
NEWS_CON VARCHAR2(900) NOT NULL
);


ALTER TABLE  NEWS ADD CONSTRAINT PK_NEWS PRIMARY KEY (NEWS_ID);








DROP TABLE RATE CASCADE CONSTRAINTS;
CREATE TABLE RATE (
RATE_ID VARCHAR2(20) NOT NULL,
NEWS_ID VARCHAR2(20) NOT NULL
);


ALTER TABLE RATE ADD CONSTRAINT PK_RATE PRIMARY KEY (RATE_ID);


--商品類別
DROP TABLE PRODUCT_CATEGORY CASCADE CONSTRAINTS;
 CREATE TABLE PRODUCT_CATEGORY (
 PRODUCT_CATEGORY_ID NUMBER(10,0) NOT NULL,
 PRODUCT_CATEGORY_NAME VARCHAR2(100)  NOT NULL


);


ALTER TABLE PRODUCT_CATEGORY ADD CONSTRAINT PK_PRODUCT_CATEGORY PRIMARY KEY (PRODUCT_CATEGORY_ID);


DROP SEQUENCE PRODUCT_CATEGORY_SEQ;
CREATE SEQUENCE PRODUCT_CATEGORY_SEQ
INCREMENT BY 10
START WITH 10
NOMAXVALUE
NOCYCLE
NOCACHE;




DROP TABLE QA_LIST CASCADE CONSTRAINTS;
CREATE TABLE QA_LIST (
LIST_ID VARCHAR2(20) NOT NULL,
LIST_NAME  VARCHAR2(100)NOT NULL
);


ALTER TABLE QA_LIST ADD CONSTRAINT PK_QA_LIST PRIMARY KEY (LIST_ID);






DROP TABLE WEATHER CASCADE CONSTRAINTS;
CREATE TABLE WEATHER (
NEWS_ID VARCHAR2(20) NOT NULL,
WEATHER_ID VARCHAR2(20) NOT NULL
);


ALTER TABLE WEATHER ADD CONSTRAINT PK_WEATHER PRIMARY KEY (NEWS_ID);




DROP TABLE FAQ CASCADE CONSTRAINTS;
CREATE TABLE FAQ (
FAQ_ID VARCHAR2(20) NOT NULL,
FAQ_CONTENT VARCHAR2(900) NOT NULL
);


ALTER TABLE FAQ ADD CONSTRAINT PK_FAQ PRIMARY KEY (FAQ_ID);


--旅遊記標籤名稱
DROP TABLE BLOG_TAG_NAME CASCADE CONSTRAINTS;
CREATE TABLE BLOG_TAG_NAME (
BTN_ID VARCHAR2(20) NOT NULL,
BTN_CLASS VARCHAR2(20) NOT NULL,
BTN_NAME VARCHAR2(100) NOT NULL
);


ALTER TABLE BLOG_TAG_NAME ADD CONSTRAINT PK_BLOG_TAG_NAME PRIMARY KEY (BTN_ID);


--景點
DROP TABLE ATTRACTIONS CASCADE CONSTRAINTS;
CREATE TABLE ATTRACTIONS (
ATT_NO VARCHAR2(10) NOT NULL,
ATT_NAME VARCHAR2(60),
ATT_LAT NUMBER(8,6),
ATT_LON NUMBER(9,6),
COUNTRY VARCHAR2(60),
ATT_INFORMATION CLOB,
ATT_PICTURE BLOB,
ATT_ADDRESS VARCHAR2(300),
ATT_STATUS NUMBER(1,0)
);


ALTER TABLE ATTRACTIONS ADD CONSTRAINT PK_ATTRACTIONS PRIMARY KEY (ATT_NO);


--廣告
DROP TABLE AD CASCADE CONSTRAINTS;
CREATE TABLE AD (
 AD_ID VARCHAR2(20) NOT NULL,
 AD_TITLE VARCHAR2(100) NOT NULL,
 AD_TEXT  VARCHAR2(300) NOT NULL,
 AD_LINK  VARCHAR2(200) NOT NULL,
 AD_PIC BLOB,
 AD_PREADDTIME TIMESTAMP,
 AD_PREOFFTIME TIMESTAMP,
 AD_ACTADDTIME TIMESTAMP,
 AD_ACTOFFTIME TIMESTAMP,
 AD_STAT NUMBER(5) NOT NULL,
 CLICKCOUNT NUMBER(15)
);


ALTER TABLE AD ADD CONSTRAINT PK_AD PRIMARY KEY (AD_ID);




DROP TABLE PHOTO_TAG CASCADE CONSTRAINTS;
CREATE TABLE PHOTO_TAG (
PHOTO_TAG_NO         VARCHAR2(20)         NOT NULL,
TAG_CONTENT          VARCHAR2(20)         NOT NULL
);


ALTER TABLE PHOTO_TAG ADD CONSTRAINT PK_PHOTO_TAG PRIMARY KEY (PHOTO_TAG_NO);




DROP TABLE ADMIN CASCADE CONSTRAINTS;
CREATE TABLE ADMIN (
ADMIN_ID                    VARCHAR2(20)        NOT NULL,
ADMIN_ACCOUNT            VARCHAR2(20)        NOT NULL,
ADMIN_PASSWORD           VARCHAR2(20)        NOT NULL,
ADMIN_NAME           VARCHAR2(20)        NOT NULL,
ADMIN_MAIL                   VARCHAR2(50)        NOT NULL,
ADMIN_PHONE           VARCHAR2(20)        NOT NULL
);


ALTER TABLE ADMIN ADD CONSTRAINT PK_ADMIN PRIMARY KEY (ADMIN_ID);


--聊天對話
DROP TABLE CHATROOM CASCADE CONSTRAINTS;
CREATE TABLE CHATROOM (
 CHATROOM_ID VARCHAR2(20) NOT NULL,
 CHATROOM_NAME VARCHAR2(100) NOT NULL,
 CHATREC CLOB
);


ALTER TABLE CHATROOM ADD CONSTRAINT PK_CHATROOM PRIMARY KEY (CHATROOM_ID);




--超商取貨城市
DROP TABLE STORE_711_CITY CASCADE CONSTRAINTS;
CREATE TABLE STORE_711_CITY (
STORE_711_CITY_ID NUMBER(10,0)  NOT NULL,
STORE_711_CITY_NAME VARCHAR2(100)  NOT NULL
);




ALTER TABLE STORE_711_CITY  ADD CONSTRAINT PK_STORE_711_CITY  PRIMARY KEY (STORE_711_CITY_ID);




DROP SEQUENCE STORE_CITY_SEQ;
CREATE SEQUENCE STORE_CITY_SEQ
INCREMENT BY 1
START WITH 10
NOMAXVALUE
NOCYCLE
NOCACHE;


--超商取貨行政區
DROP TABLE STORE_711_DIST CASCADE CONSTRAINTS;
CREATE TABLE STORE_711_DIST (
 STORE_711_DIST_ID NUMBER(10,0)  NOT NULL,
 STORE_711_CITY_ID NUMBER(10,0) NOT NULL,
 STORE_711_DIST_NAME VARCHAR2(100)  NOT NULL
);


ALTER TABLE STORE_711_DIST ADD CONSTRAINT PK_STORE_711_DIST PRIMARY KEY (STORE_711_DIST_ID);


DROP SEQUENCE STORE_DIST_SEQ;
CREATE SEQUENCE STORE_DIST_SEQ
INCREMENT BY 1
START WITH 100
NOMAXVALUE
NOCYCLE
NOCACHE;








DROP TABLE ABOUT_US CASCADE CONSTRAINTS;
CREATE TABLE ABOUT_US (
ABOUT_US_ID VARCHAR2(20) NOT NULL,
ABOUT_CONTENT  CLOB NOT NULL
);










--超商取貨
DROP TABLE STORE_711 CASCADE CONSTRAINTS;
CREATE TABLE STORE_711 (
 STORE_711_ID NUMBER(10,0)  NOT NULL,
 STORE_711_DIST_ID NUMBER(10,0)  NOT NULL,
 STORE_711_NAME VARCHAR2(100)  NOT NULL,
 STORE_711_ADDR VARCHAR2(300)  NOT NULL,
 STORE_711_CITY_NAME VARCHAR2(100)  NOT NULL,
 STORE_711_DIST_NAME VARCHAR2(100)  NOT NULL
);


ALTER TABLE STORE_711 ADD CONSTRAINT PK_STORE_711 PRIMARY KEY (STORE_711_ID);




DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (


  MEM_ID                              VARCHAR2(20)  NOT NULL, 
  MEM_ACCOUNT                    VARCHAR2(50)  NOT NULL, 
  MEM_PASSWORD            VARCHAR2(20)  NOT NULL, 
  MEM_NAME                    VARCHAR2(20)  NOT NULL,  
  MEM_SEX                           NUMBER(3), 
  MEM_ADDRESS                 VARCHAR2(200),
  MEM_BIRTHDAY                 DATE,
  MEM_PHONE                 VARCHAR2(20),
  MEM_PROFILE                 VARCHAR2(200),
  MEM_PHOTO                 BLOB,
  MEM_STATE                 NUMBER(3)              NOT NULL,
  DELIVERY_ADDRESS_1        VARCHAR2(300),                
  DELIVERY_ADDRESS_2        VARCHAR2(300),
  DELIVERY_ADDRESS_3        VARCHAR2(300),
  STORE_ADDR_1                VARCHAR2(300),
  STORE_ADDR_2                VARCHAR2(300),
  STORE_ADDR_3                VARCHAR2(300),
  STORE_NAME_1                VARCHAR2(200),
  STORE_NAME_2                VARCHAR2(200),
  STORE_NAME_3                VARCHAR2(200),
  STORE_NO_2                NUMBER(20),
  STORE_NO_3                 NUMBER(20),
  STORE_NO_1                 NUMBER(20)
);


ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEM_ID);


--商品
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
CREATE TABLE PRODUCT (
 PRODUCT_ID NUMBER(10,0)  NOT NULL,
 PRODUCT_CATEGORY_ID NUMBER(10,0)  NOT NULL,
 PRODUCT_MEM_ID  VARCHAR2(20)  NOT NULL, 
 PRODUCT_NAME VARCHAR2(300)  NOT NULL, 
 PRODUCT_PRICE NUMBER(10,0)  NOT NULL,
 PRODUCT_DESCR CLOB,
 PRODUCT_STOCK NUMBER(10,0)  NOT NULL,
 PRODUCT_STATUS NUMBER(1,0)  NOT NULL,
 PRODUCT_DATE  TIMESTAMP NOT NULL,
 PRODUCT_PHOTO_1 BLOB,
 PRODUCT_PHOTO_2 BLOB,
 PRODUCT_PHOTO_3 BLOB,
 PRODUCT_PHOTO_4 BLOB,
 PRODUCT_PHOTO_5 BLOB
);


ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID);
DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ
INCREMENT BY 1
START WITH 1001
NOMAXVALUE
NOCYCLE
NOCACHE;




DROP TABLE QUESTION CASCADE CONSTRAINTS;
CREATE TABLE QUESTION (
QUESTION_ID VARCHAR2(20) NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL,
QUESTION_CONTENT CLOB NOT NULL,
BUILD_DATE DATE NOT NULL
);


ALTER TABLE QUESTION ADD CONSTRAINT PK_QUESTION PRIMARY KEY (QUESTION_ID);






DROP TABLE QA_REPLY CASCADE CONSTRAINTS;
CREATE TABLE QA_REPLY (
REPLY_ID VARCHAR2(20) NOT NULL,
QUESTION_ID VARCHAR2(20) NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL,
REPLY_CONTENT CLOB NOT NULL,
REPLY_DATE DATE NOT NULL
);


ALTER TABLE QA_REPLY ADD CONSTRAINT PK_QA_REPLY PRIMARY KEY (REPLY_ID);


--好友名單
DROP TABLE FRIEND CASCADE CONSTRAINTS;
CREATE TABLE FRIEND (
 FRI_ID VARCHAR2(20) NOT NULL,
 MEMID_SELF VARCHAR2(20) NOT NULL,
 MEMID_FRI VARCHAR2(20) NOT NULL,
 FRI_TIME TIMESTAMP,
 FRI_STAT NUMBER(5)
);


ALTER TABLE FRIEND ADD CONSTRAINT PK_FRIEND PRIMARY KEY (FRI_ID);


--收藏商品
DROP TABLE PRODUCT_WISHLIST CASCADE CONSTRAINTS;
CREATE TABLE PRODUCT_WISHLIST (
 WISHLIST_PRODUCT_ID NUMBER(10,0)  NOT NULL,
 WISHLIST_MEM_ID VARCHAR2(20) NOT NULL,
 PRODUCT_WISHLIST_TIME TIMESTAMP
);


ALTER TABLE PRODUCT_WISHLIST ADD CONSTRAINT PK_PRODUCT_WISHLIST PRIMARY KEY (WISHLIST_PRODUCT_ID,WISHLIST_MEM_ID);




DROP TABLE QA_COLLECT CASCADE CONSTRAINTS;
CREATE TABLE QA_COLLECT (
QUESTION_ID VARCHAR2(20) NOT NULL,
MEM_ID VARCHAR(20) NOT NULL
);


ALTER TABLE QA_COLLECT ADD CONSTRAINT PK_QA_COLLECT PRIMARY KEY (QUESTION_ID,MEM_ID);


--檢舉商品
DROP TABLE PRODUCT_REPORT CASCADE CONSTRAINTS;
CREATE TABLE PRODUCT_REPORT (
 PROD_REPORT_PRODUCT_ID NUMBER(10,0)  NOT NULL,
 PROD_REPORT_MEM_ID VARCHAR2(20) NOT NULL,
 PROD_REPORT_REASON VARCHAR2(300) NOT NULL,
 PROD_REPORT_TIME TIMESTAMP,
 PROD_REPORT_STATUS NUMBER(1,0)
);


ALTER TABLE PRODUCT_REPORT ADD CONSTRAINT PK_PRODUCT_REPORT PRIMARY KEY (PROD_REPORT_PRODUCT_ID,PROD_REPORT_MEM_ID);




DROP TABLE QA_REPORT CASCADE CONSTRAINTS;
CREATE TABLE QA_REPORT (
QUESTION_ID VARCHAR2(20) NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL,
QA_STATE NUMBER(1) NOT NULL
);


ALTER TABLE QA_REPORT ADD CONSTRAINT PK_QA_REPORT PRIMARY KEY (QUESTION_ID,MEM_ID);




DROP TABLE MEMBER_REPORT CASCADE CONSTRAINTS;
CREATE TABLE MEMBER_REPORT (
 MEM_ID_REPORT                 VARCHAR2(20)                 NOT NULL,
 MEM_ID_REPORTED         VARCHAR2(20)                 NOT NULL,
 REPORT_TIME                TIMESTAMP                            NOT NULL,
 REPORT_REASON                VARCHAR2(200)         NOT NULL,
 MEM_REP_STA                NUMBER(1)                NOT NULL
);


ALTER TABLE MEMBER_REPORT ADD CONSTRAINT PK_MEM_ID_REPORT PRIMARY KEY (MEM_ID_REPORT,MEM_ID_REPORTED);




DROP TABLE PHOTO_WALL CASCADE CONSTRAINTS;
CREATE TABLE PHOTO_WALL (
PHOTO_NO   VARCHAR2(20)                 NOT NULL,
MEM_ID         VARCHAR2(20)                 NOT NULL,
PO_TIME        TIMESTAMP                         NOT NULL,
PHOTO        BLOB,
PHOTO_STA   NUMBER(3)     NOT NULL,
PHOTO_CONTENT VARCHAR2(500)    
);


ALTER TABLE PHOTO_WALL ADD CONSTRAINT PK_PHOTO_WALL PRIMARY KEY (PHOTO_NO);


--聊天對話參與名單
DROP TABLE CHATROOM_JOIN CASCADE CONSTRAINTS;
CREATE TABLE CHATROOM_JOIN (
 CHATROOM_ID VARCHAR2(20) NOT NULL,
 JOIN_MEMID VARCHAR2(20) NOT NULL
);


ALTER TABLE CHATROOM_JOIN ADD CONSTRAINT PK_CHATROOM_JOIN PRIMARY KEY (CHATROOM_ID,JOIN_MEMID);


--行程
DROP TABLE TRIP CASCADE CONSTRAINTS;
CREATE TABLE TRIP (
 TRIP_NO VARCHAR2(10) NOT NULL,
 MEM_ID VARCHAR2(20),
TRIP_NAME VARCHAR2(60),
TRIP_STARTDAY DATE,
TRIP_DAYS NUMBER(3,0) NOT NULL,
TRIP_VIEWS NUMBER(20,0) NOT NULL,
TRIP_STATUS NUMBER(1,0) NOT NULL
);


ALTER TABLE TRIP ADD CONSTRAINT PK_TRIP PRIMARY KEY (TRIP_NO);


--行程天
DROP TABLE TRIP_DAYS CASCADE CONSTRAINTS;
CREATE TABLE TRIP_DAYS (
 TRIPDAY_NO VARCHAR2(10) NOT NULL,
 TRIP_NO VARCHAR2(10) NOT NULL,
TRIPDAY_DAYS NUMBER(3,0) NOT NULL,
TRIPDAY_DATE DATE,
TRIPDAY_HOTELNAME VARCHAR2(60),
TRIPDAY_HOTELSTART NUMBER(5,0),
TRIPDAY_HOTELNOTE CLOB,
TRIPDAY_HOTELCOST NUMBER(20,0)
);


ALTER TABLE TRIP_DAYS ADD CONSTRAINT PK_TRIP_DAYS PRIMARY KEY (TRIPDAY_NO);


--訂單
DROP TABLE ORD CASCADE CONSTRAINTS;
CREATE TABLE ORD (
  ORDER_ID VARCHAR2(15) NOT NULL, 
  BUYER_MEM_ID VARCHAR2(20)  NOT NULL, 
  SELLER_MEM_ID VARCHAR2(20)  NOT NULL,
  ORDER_ADDRESS VARCHAR2(300)  NOT NULL,
  PAYMENT_STATUS  NUMBER(1,0) NOT NULL,
  PAYMENT_METHOD NUMBER(1,0) NOT NULL,
  SHIPMENT_STATUS NUMBER(1,0) NOT NULL,
  ORDER_DATE TIMESTAMP,
  ORDER_STATUS NUMBER(1,0) NOT NULL,
  ORDER_TOTAL NUMBER(10,0) NOT NULL,
  ORDER_ITEM  NUMBER(10,0) NOT NULL,
  CANCEL_REASON NUMBER(2,0),
  STOB_RATING NUMBER(1,0),
  STOB_RATING_DESCR VARCHAR2(200),
  BTOS_RATING NUMBER(1,0),
  BTOS_RATING_DESCR VARCHAR2(200),
  SHIPMENT_ID VARCHAR2(100),
  SHIPMENT_METHOD NUMBER(1,0),
  ORD_STORE_711_NAME VARCHAR2(100)
);


ALTER TABLE ORD ADD CONSTRAINT PK_ORD PRIMARY KEY (ORDER_ID);


DROP SEQUENCE ORD_SEQ;
CREATE SEQUENCE ORD_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


--購買清單
DROP TABLE ORDER_DETAILS CASCADE CONSTRAINTS;
CREATE TABLE ORDER_DETAILS (
 DETAILS_ORDER_ID VARCHAR2(15) NOT NULL, 
 DETAILS_PRODUCT_ID NUMBER(10,0)  NOT NULL,
 DETAILS_ORDER_QTY NUMBER(10,0)  NOT NULL,
 DETAILS_ORDER_TOTAL NUMBER(10,0)  NOT NULL
);


ALTER TABLE ORDER_DETAILS ADD CONSTRAINT PK_ORDER_DETAILS PRIMARY KEY (DETAILS_ORDER_ID,DETAILS_PRODUCT_ID);




DROP TABLE NOTICE CASCADE CONSTRAINTS;
CREATE TABLE NOTICE (
NOTICE_ID VARCHAR2(20) NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL
);


ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_ID);


--交通行程
DROP TABLE TRAFFIC_TRIP CASCADE CONSTRAINTS;
CREATE TABLE TRAFFIC_TRIP (
TRATRIP_NO VARCHAR2(10) NOT NULL,
TRIPDAY_NO VARCHAR2(10) NOT NULL,
TRATRIP_TYPE NUMBER(2,0),
TRATRIP_COST NUMBER(20,0),
TRATRIP_START NUMBER(5,0),
TRATRIP_END NUMBER(5,0),
TRIP_ORDER NUMBER(3,0),
TRATRIP_NAME VARCHAR2(60),
TRATRIP_NOTE CLOB
);


ALTER TABLE TRAFFIC_TRIP ADD CONSTRAINT PK_TRAFFIC_TRIP PRIMARY KEY (TRATRIP_NO);




DROP TABLE QA_CLASSIFICATION CASCADE CONSTRAINTS;
CREATE TABLE QA_CLASSIFICATION (
 LIST_ID VARCHAR2(20) NOT NULL,
 QUESTION_ID VARCHAR2(20) NOT NULL
);


ALTER TABLE QA_CLASSIFICATION ADD CONSTRAINT PK_QA_CLASSIFICATION PRIMARY KEY (LIST_ID,QUESTION_ID);




DROP TABLE GRP CASCADE CONSTRAINTS;
CREATE TABLE GRP (
GRP_ID                    VARCHAR2(20)                NOT NULL,
MEM_ID                    VARCHAR2(20)                NOT NULL,
GRP_START                TIMESTAMP,
GRP_END                   TIMESTAMP,
GRP_CNT                   NUMBER(5)                NOT NULL,
GRP_ACPT                NUMBER(5)                NOT NULL,
TRIP_NO                 VARCHAR2(20)        NOT NULL,                
TRIP_START                TIMESTAMP                NOT NULL,
TRIP_END                TIMESTAMP                NOT NULL,
TRIP_LOCALE            VARCHAR2(300)        NOT NULL,
TRIP_DETAILS        VARCHAR2(3000)        NOT NULL,
GRP_PHOTO                BLOB,
GRP_STATUS                NUMBER(5)                NOT NULL,
CHATROOM_ID            VARCHAR2(20)                
);


ALTER TABLE GRP ADD CONSTRAINT PK_GRP PRIMARY KEY (GRP_ID);




DROP TABLE GRP_MEM CASCADE CONSTRAINTS;
CREATE TABLE GRP_MEM (
 GRP_ID                 VARCHAR2(20)                 NOT NULL,
 MEM_ID                 VARCHAR2(20)                 NOT NULL,
GRP_LEADER        VARCHAR2(5)                NOT NULL
);


ALTER TABLE GRP_MEM ADD CONSTRAINT PK_GRP_MEM PRIMARY KEY (GRP_ID,MEM_ID);




DROP TABLE GRP_COM CASCADE CONSTRAINTS;
CREATE TABLE GRP_COM (
 GRP_COM_ID         VARCHAR2(20)                 NOT NULL,
 GRP_ID                VARCHAR2(20)                 NOT NULL,
 MEM_ID                 VARCHAR2(20)                 NOT NULL,
 GRP_COM                    VARCHAR2(500)                 NOT NULL
);


ALTER TABLE GRP_COM ADD CONSTRAINT PK_GRP_COM PRIMARY KEY (GRP_COM_ID);


--行程收藏
DROP TABLE TRIP_COLLECT CASCADE CONSTRAINTS;
CREATE TABLE TRIP_COLLECT (
TRIP_NO VARCHAR2(10) NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL
);


ALTER TABLE TRIP_COLLECT ADD CONSTRAINT PK_TRIP_COLLECT PRIMARY KEY (TRIP_NO,MEM_ID);


--旅遊記
DROP TABLE BLOG CASCADE CONSTRAINTS;
CREATE TABLE BLOG (
BLOG_ID VARCHAR2(20) NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL,
BLOG_DATE TIMESTAMP(0) NOT NULL,
BLOG_COVERIMAGE BLOB,
BLOG_TITLE VARCHAR2(100) NOT NULL,
BLOG_CONTENT CLOB NOT NULL,
TRAVEL_DATE DATE NOT NULL,
TRIP_NO VARCHAR2(10) NOT NULL,
BLOG_VIEWS NUMBER(10) NOT NULL,
BLOG_STATUS NUMBER(1) NOT NULL
);


ALTER TABLE BLOG  ADD CONSTRAINT PK_BLOG  PRIMARY KEY (BLOG_ID);


--旅遊記收藏
DROP TABLE BLOG_COLLECT CASCADE CONSTRAINTS;
CREATE TABLE BLOG_COLLECT (
MEM_ID VARCHAR2(20) NOT NULL,
BLOG_ID VARCHAR2(20) NOT NULL
);


ALTER TABLE BLOG_COLLECT ADD CONSTRAINT PK_BLOG_COLLECT PRIMARY KEY (BLOG_ID,MEM_ID);


--旅遊記標籤
DROP TABLE BLOG_TAG CASCADE CONSTRAINTS;
CREATE TABLE BLOG_TAG (
BLOG_ID VARCHAR2(20) NOT NULL,
BTN_ID VARCHAR2(20) NOT NULL
);


ALTER TABLE BLOG_TAG ADD CONSTRAINT PK_BLOG_TAG PRIMARY KEY (BTN_ID,BLOG_ID);




--旅遊記檢舉
DROP TABLE BLOG_REPORT CASCADE CONSTRAINTS;
CREATE TABLE BLOG_REPORT (
BLOG_ID VARCHAR2(20) NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL,
BR_STATUS NUMBER(1) NOT NULL
);


ALTER TABLE BLOG_REPORT ADD CONSTRAINT PK_BLOG_REPORT PRIMARY KEY (BLOG_ID,MEM_ID);


--旅遊記留言
DROP TABLE BLOG_MESSAGE CASCADE CONSTRAINTS;
CREATE TABLE BLOG_MESSAGE (
MESSAGE_ID VARCHAR2(20) NOT NULL,
BLOG_ID VARCHAR2(20) NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL,
BLOG_MESSAGE CLOB NOT NULL,
BM_STATUS NUMBER(1) NOT NULL
);


ALTER TABLE BLOG_MESSAGE ADD CONSTRAINT PK_BLOG_MESSAGE PRIMARY KEY (MESSAGE_ID);


--旅遊記留言檢舉
DROP TABLE BLOG_MESSAGE_REPORT CASCADE CONSTRAINTS;
CREATE TABLE BLOG_MESSAGE_REPORT (
MEM_ID VARCHAR2(20) NOT NULL,
MESSAGE_ID VARCHAR2(20) NOT NULL,
BMR_STATUS NUMBER(1) NOT NULL
);


ALTER TABLE BLOG_MESSAGE_REPORT ADD CONSTRAINT PK_BLOG_MESSAGE_REPORT PRIMARY KEY (MESSAGE_ID,MEM_ID);


--景點行程
DROP TABLE ATTRACTIONS_TRIP CASCADE CONSTRAINTS;
CREATE TABLE ATTRACTIONS_TRIP (
ATTTRIP_NO VARCHAR2(10) NOT NULL,
ATT_NO VARCHAR2(10) NOT NULL,
TRIPDAY_NO VARCHAR2(10) NOT NULL,
ATTTRIP_COST NUMBER(20,0),
ATTTRIP_START NUMBER(5,0),
ATTTRIP_END NUMBER(5,0),
TRIP_ORDER NUMBER(3,0),
ATTTRIP_NOTE CLOB
);


ALTER TABLE ATTRACTIONS_TRIP ADD CONSTRAINT PK_ATTRACTIONS_TRIP PRIMARY KEY (ATTTRIP_NO);


--景點共同編輯待審核
DROP TABLE ATTRACTIONS_EDIT CASCADE CONSTRAINTS;
CREATE TABLE ATTRACTIONS_EDIT (
ATTEDIT_NO VARCHAR2(10) NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL,
ATTEDIT_DATE DATE NOT NULL,
ATT_NO VARCHAR2(10),
ATT_NAME VARCHAR(60),
ATT_LAT NUMBER(8,6),
ATT_LON NUMBER(9,6),
COUNTRY VARCHAR2(60),
ATT_INFORMATION CLOB,
ATT_PICTURE BLOB,
ATT_ADDRESS VARCHAR2(200)
);


ALTER TABLE ATTRACTIONS_EDIT ADD CONSTRAINT PK_ATTRACTIONS_EDIT PRIMARY KEY (ATTEDIT_NO);




DROP TABLE GRP_REPORT CASCADE CONSTRAINTS;
CREATE TABLE GRP_REPORT (
 GRP_ID                 VARCHAR2(20)                 NOT NULL,
 MEM_ID                VARCHAR2(20)                 NOT NULL,
REPORT_REASON        VARCHAR2(300)                 NOT NULL,
REPORT_TIME        TIMESTAMP                 NOT NULL,
GRP_REP_STA        NUMBER(1)                 NOT NULL
);


ALTER TABLE GRP_REPORT ADD CONSTRAINT PK_GRP_REPORT PRIMARY KEY (GRP_ID,MEM_ID);




DROP TABLE PHOTO_REPORT CASCADE CONSTRAINTS;
CREATE TABLE PHOTO_REPORT (
 PHOTO_NO                 VARCHAR2(20)                 NOT NULL,
 MEM_ID                 VARCHAR2(20)                 NOT NULL,
 REPORT_REASON  VARCHAR2(200)                 NOT NULL,
 REPORT_TIME        TIMESTAMP                         NOT NULL,
 PHO_REP_STATS        NUMBER(1)                NOT NULL                        
);


ALTER TABLE PHOTO_REPORT ADD CONSTRAINT PK_PHOTO_REPORT PRIMARY KEY (PHOTO_NO,MEM_ID);




DROP TABLE PHOTO_TAG_LIST CASCADE CONSTRAINTS;
CREATE TABLE PHOTO_TAG_LIST (
 PHOTO_TAG_NO         VARCHAR2(20)                NOT NULL,
 PHOTO_NO                  VARCHAR2(20)                 NOT NULL
);


ALTER TABLE PHOTO_TAG_LIST ADD CONSTRAINT PK_PHOTO_TAG_LIST PRIMARY KEY (PHOTO_TAG_NO,PHOTO_NO);




ALTER TABLE RATE ADD CONSTRAINT FK_RATE_0 FOREIGN KEY (NEWS_ID) REFERENCES  NEWS (NEWS_ID);




ALTER TABLE WEATHER ADD CONSTRAINT FK_WEATHER_0 FOREIGN KEY (NEWS_ID) REFERENCES  NEWS (NEWS_ID);




ALTER TABLE STORE_711_DIST ADD CONSTRAINT FK_STORE_711_DIST_0 FOREIGN KEY (STORE_711_CITY_ID) REFERENCES STORE_711_CITY (STORE_711_CITY_ID);




ALTER TABLE STORE_711 ADD CONSTRAINT FK_STORE_711_0 FOREIGN KEY (STORE_711_DIST_ID) REFERENCES STORE_711_DIST (STORE_711_DIST_ID);




ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_0 FOREIGN KEY (STORE_NO_1) REFERENCES STORE_711 (STORE_711_ID);
ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_1 FOREIGN KEY (STORE_NO_2) REFERENCES STORE_711 (STORE_711_ID);
ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_2 FOREIGN KEY (STORE_NO_3) REFERENCES STORE_711 (STORE_711_ID);




ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_0 FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (PRODUCT_CATEGORY_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_1 FOREIGN KEY (PRODUCT_MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE QUESTION ADD CONSTRAINT FK_QUESTION_0 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE QA_REPLY ADD CONSTRAINT FK_QA_REPLY_0 FOREIGN KEY 
(QUESTION_ID) REFERENCES QUESTION (QUESTION_ID);
ALTER TABLE QA_REPLY ADD CONSTRAINT FK_QA_REPLY_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE FRIEND ADD CONSTRAINT FK_FRIEND_0 FOREIGN KEY (MEMID_SELF) REFERENCES MEMBER (MEM_ID);
ALTER TABLE FRIEND ADD CONSTRAINT FK_FRIEND_1 FOREIGN KEY (MEMID_FRI) REFERENCES MEMBER (MEM_ID);




ALTER TABLE PRODUCT_WISHLIST ADD CONSTRAINT FK_PRODUCT_WISHLIST_0 FOREIGN KEY (WISHLIST_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE PRODUCT_WISHLIST ADD CONSTRAINT FK_PRODUCT_WISHLIST_1 FOREIGN KEY (WISHLIST_MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE QA_COLLECT ADD CONSTRAINT FK_QA_COLLECT_0 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (QUESTION_ID);
ALTER TABLE QA_COLLECT ADD CONSTRAINT FK_QA_COLLECT_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE PRODUCT_REPORT ADD CONSTRAINT FK_PRODUCT_REPORT_0 FOREIGN KEY (PROD_REPORT_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE PRODUCT_REPORT ADD CONSTRAINT FK_PRODUCT_REPORT_1 FOREIGN KEY (PROD_REPORT_MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE QA_REPORT ADD CONSTRAINT FK_QA_REPORT_0 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (QUESTION_ID);
ALTER TABLE QA_REPORT ADD CONSTRAINT FK_QA_REPORT_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE MEMBER_REPORT ADD CONSTRAINT FK_MEMBER_REPORT_0 FOREIGN KEY (MEM_ID_REPORT) REFERENCES MEMBER (MEM_ID);
ALTER TABLE MEMBER_REPORT ADD CONSTRAINT FK_MEMBER_REPORT_1 FOREIGN KEY (MEM_ID_REPORTED) REFERENCES MEMBER (MEM_ID);




ALTER TABLE PHOTO_WALL ADD CONSTRAINT FK_PHOTO_WALL_0 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE CHATROOM_JOIN ADD CONSTRAINT FK_CHATROOM_JOIN_0 FOREIGN KEY (CHATROOM_ID) REFERENCES CHATROOM (CHATROOM_ID);
ALTER TABLE CHATROOM_JOIN ADD CONSTRAINT FK_CHATROOM_JOIN_1 FOREIGN KEY (JOIN_MEMID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE TRIP ADD CONSTRAINT FK_TRIP_0 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE TRIP_DAYS ADD CONSTRAINT FK_TRIP_DAYS_0 FOREIGN KEY (TRIP_NO) REFERENCES TRIP (TRIP_NO);




ALTER TABLE ORD ADD CONSTRAINT FK_ORD_0 FOREIGN KEY (BUYER_MEM_ID) REFERENCES MEMBER (MEM_ID);
ALTER TABLE ORD ADD CONSTRAINT FK_ORD_1 FOREIGN KEY (SELLER_MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS_0 FOREIGN KEY (DETAILS_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS_1 FOREIGN KEY (DETAILS_ORDER_ID) REFERENCES ORD (ORDER_ID);




ALTER TABLE  NOTICE ADD CONSTRAINT FK_NOTICE_0 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE TRAFFIC_TRIP ADD CONSTRAINT FK_TRAFFIC_TRIP_0 FOREIGN KEY (TRIPDAY_NO) REFERENCES TRIP_DAYS (TRIPDAY_NO);




ALTER TABLE QA_CLASSIFICATION ADD CONSTRAINT FK_QA_CLASSIFICATION_0 FOREIGN KEY (LIST_ID) REFERENCES QA_LIST (LIST_ID);
ALTER TABLE QA_CLASSIFICATION ADD CONSTRAINT FK_QA_CLASSIFICATION_1 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (QUESTION_ID);




ALTER TABLE GRP ADD CONSTRAINT FK_GRP_0 FOREIGN KEY (TRIP_NO) REFERENCES TRIP (TRIP_NO);
ALTER TABLE GRP ADD CONSTRAINT FK_GRP_1 FOREIGN KEY (CHATROOM_ID) REFERENCES CHATROOM (CHATROOM_ID);
ALTER TABLE GRP ADD CONSTRAINT FK_GRP_2 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE GRP_MEM ADD CONSTRAINT FK_GRP_MEM_0 FOREIGN KEY (GRP_ID) REFERENCES GRP (GRP_ID);
ALTER TABLE GRP_MEM ADD CONSTRAINT FK_GRP_MEM_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE GRP_COM ADD CONSTRAINT FK_GRP_COM_0 FOREIGN KEY (GRP_ID) REFERENCES GRP (GRP_ID);
ALTER TABLE GRP_COM ADD CONSTRAINT FK_GRP_COM_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE TRIP_COLLECT ADD CONSTRAINT FK_TRIP_COLLECT_0 FOREIGN KEY (TRIP_NO) REFERENCES TRIP (TRIP_NO);
ALTER TABLE TRIP_COLLECT ADD CONSTRAINT FK_TRIP_COLLECT_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE BLOG ADD CONSTRAINT FK_BLOG_0 FOREIGN KEY (TRIP_NO) REFERENCES TRIP (TRIP_NO);
ALTER TABLE BLOG ADD CONSTRAINT FK_BLOG_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE BLOG_COLLECT ADD CONSTRAINT FK_BLOG_COLLECT_0 FOREIGN KEY (BLOG_ID) REFERENCES BLOG (BLOG_ID);
ALTER TABLE BLOG_COLLECT ADD CONSTRAINT FK_BLOG_COLLECT_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE BLOG_TAG ADD CONSTRAINT FK_BLOG_TAG_0 FOREIGN KEY (BTN_ID) REFERENCES BLOG_TAG_NAME (BTN_ID);
ALTER TABLE BLOG_TAG ADD CONSTRAINT FK_BLOG_TAG_1 FOREIGN KEY (BLOG_ID) REFERENCES BLOG (BLOG_ID);




ALTER TABLE BLOG_REPORT ADD CONSTRAINT FK_BLOG_REPORT_0 FOREIGN KEY (BLOG_ID) REFERENCES BLOG (BLOG_ID);
ALTER TABLE BLOG_REPORT ADD CONSTRAINT FK_BLOG_REPORT_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE BLOG_MESSAGE ADD CONSTRAINT FK_BLOG_MESSAGE_0 FOREIGN KEY (BLOG_ID) REFERENCES BLOG (BLOG_ID);
ALTER TABLE BLOG_MESSAGE ADD CONSTRAINT FK_BLOG_MESSAGE_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE BLOG_MESSAGE_REPORT ADD CONSTRAINT FK_BLOG_MESSAGE_REPORT_0 FOREIGN KEY (MESSAGE_ID) REFERENCES BLOG_MESSAGE (MESSAGE_ID);
ALTER TABLE BLOG_MESSAGE_REPORT ADD CONSTRAINT FK_BLOG_MESSAGE_REPORT_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE ATTRACTIONS_TRIP ADD CONSTRAINT FK_ATTRACTIONS_TRIP_0 FOREIGN KEY (ATT_NO) REFERENCES ATTRACTIONS (ATT_NO);
ALTER TABLE ATTRACTIONS_TRIP ADD CONSTRAINT FK_ATTRACTIONS_TRIP_1 FOREIGN KEY (TRIPDAY_NO) REFERENCES TRIP_DAYS (TRIPDAY_NO);




ALTER TABLE ATTRACTIONS_EDIT ADD CONSTRAINT FK_ATTRACTIONS_EDIT_0 FOREIGN KEY (ATT_NO) REFERENCES ATTRACTIONS (ATT_NO);
ALTER TABLE ATTRACTIONS_EDIT ADD CONSTRAINT FK_ATTRACTIONS_EDIT_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE GRP_REPORT ADD CONSTRAINT FK_GRP_REPORT_0 FOREIGN KEY (GRP_ID) REFERENCES GRP (GRP_ID);
ALTER TABLE GRP_REPORT ADD CONSTRAINT FK_GRP_REPORT_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE PHOTO_REPORT ADD CONSTRAINT FK_PHOTO_REPORT_0 FOREIGN KEY (PHOTO_NO) REFERENCES PHOTO_WALL (PHOTO_NO);
ALTER TABLE PHOTO_REPORT ADD CONSTRAINT FK_PHOTO_REPORT_1 FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);




ALTER TABLE PHOTO_TAG_LIST ADD CONSTRAINT FK_PHOTO_TAG_LIST_0 FOREIGN KEY (PHOTO_NO) REFERENCES PHOTO_WALL (PHOTO_NO);






--NEWS
DROP SEQUENCE NEWS_SEQ;
CREATE SEQUENCE NEWS_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO NEWS (NEWS_ID,NEWS_NAME,NEWS_DATE,NEWS_CON) VALUES ('NE'||LPAD(TO_CHAR(NEWS_SEQ.NEXTVAL), 9, '0'),'TRAVEL_MAKER新增辦公室公告-台中公司',TO_DATE('2018-07-10','YYYY-MM-DD'),'親愛的客戶們，感謝大家對 TRAVEL_MAKER-台中公司的支持，為拓展業務及提供給大家更好的服務品質，台中公司於 2018/04/16 新增至：台中市西區大隆路20號10樓之11');
INSERT INTO NEWS (NEWS_ID,NEWS_NAME,NEWS_DATE,NEWS_CON) VALUES ('NE'||LPAD(TO_CHAR(NEWS_SEQ.NEXTVAL), 9, '0'),'TRAVEL_MAKER營業時間異動公告',TO_DATE('2018-08-10','YYYY-MM-DD'),'親愛的客戶們，感謝大家對 TRAVEL_MAKER的支持，為拓展業務及提供給大家更好的服務品質，8/7-8/8父親節連假公休');
INSERT INTO NEWS (NEWS_ID,NEWS_NAME,NEWS_DATE,NEWS_CON) VALUES ('NE'||LPAD(TO_CHAR(NEWS_SEQ.NEXTVAL), 9, '0'),'狂賀!TRAVEL_MAKER 5年勇奪10座金質旅遊獎認證!',TO_DATE('2018-07-11','YYYY-MM-DD'),'親愛的客戶們，感謝大家對TRAVEL_MAKER的支持，創立5年來，努力耕耘。對於每一個細節的用心，獲得顧客高度肯定，今年(2018)再度奪下3座旅遊界最高榮譽—「金質旅遊獎」殊榮，希望將這項喜悅與每一位晴天玩家分享，也期盼未來能不斷向前，提供最頂級的服務。');
--RATE


--PRODUCT_CATEGORY
--商品類別
DROP SEQUENCE PRODUCT_CATEGORY_SEQ;
CREATE SEQUENCE PRODUCT_CATEGORY_SEQ
INCREMENT BY 10
START WITH 10
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO PRODUCT_CATEGORY (PRODUCT_CATEGORY_ID,PRODUCT_CATEGORY_NAME) VALUES (PRODUCT_CATEGORY_SEQ.NEXTVAL,'票券');
INSERT INTO PRODUCT_CATEGORY (PRODUCT_CATEGORY_ID,PRODUCT_CATEGORY_NAME) VALUES (PRODUCT_CATEGORY_SEQ.NEXTVAL,'SIM卡');
INSERT INTO PRODUCT_CATEGORY (PRODUCT_CATEGORY_ID,PRODUCT_CATEGORY_NAME) VALUES (PRODUCT_CATEGORY_SEQ.NEXTVAL,'背包配件');




--TABLE QA_LIST
DROP SEQUENCE QA_LIST_SEQ;
CREATE SEQUENCE QA_LIST_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO QA_LIST (LIST_ID,LIST_NAME) VALUES ('LI'||LPAD(TO_CHAR(QA_LIST_SEQ.NEXTVAL), 9, '0'),'台灣');
INSERT INTO QA_LIST (LIST_ID,LIST_NAME) VALUES ('LI'||LPAD(TO_CHAR(QA_LIST_SEQ.NEXTVAL), 9, '0'),'日本');
INSERT INTO QA_LIST (LIST_ID,LIST_NAME) VALUES ('LI'||LPAD(TO_CHAR(QA_LIST_SEQ.NEXTVAL), 9, '0'),'香港');
INSERT INTO QA_LIST (LIST_ID,LIST_NAME) VALUES ('LI'||LPAD(TO_CHAR(QA_LIST_SEQ.NEXTVAL), 9, '0'),'歐洲');
--WEATHER


--FAQ
DROP SEQUENCE FAQ_SEQ;
CREATE SEQUENCE FAQ_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO FAQ (FAQ_ID,FAQ_CONTENT) VALUES ('FA'||LPAD(TO_CHAR(FAQ_SEQ.NEXTVAL), 9, '0'),'我如何註冊?點選右上「登入/註冊」。 您可直接透過社群帳號(FACEBOOK、GOOGLE)直接登入。或以其他電子郵件註冊，設定密碼，並通過驗證。我們會寄送電子郵件認證碼，請記得確認你的信箱，有沒有收到認證碼。');
INSERT INTO FAQ (FAQ_ID,FAQ_CONTENT) VALUES ('FA'||LPAD(TO_CHAR(FAQ_SEQ.NEXTVAL), 9, '0'),'註冊成為TRAVEL_MAKER會員需要付費嗎？TRAVEL_MAKER為免費平台，提供自助旅行愛好者查詢景點資訊、編輯行程、分享遊記與照片，以及揪團找旅伴，會員加入不需要付費。');
INSERT INTO FAQ (FAQ_ID,FAQ_CONTENT) VALUES ('FA'||LPAD(TO_CHAR(FAQ_SEQ.NEXTVAL), 9, '0'),'編輯行程時，如果搜尋不到計畫參觀的景點該怎麼辦？在TRAVEL_MAKER的地圖模式上無法搜尋到你想去的景點時，可以填寫線上意見表單，提供我們地點的經緯度，我們將會盡快將它納入地圖裡。TRAVEL_MAKER會在不久的將來提供自訂景點功能，只要你有景點的地址或座標，你可以自己設立喜歡的景點，並分享給其他旅行者。');




--BLOG_TAG_NAME
DROP SEQUENCE BTN_SEQ;
CREATE SEQUENCE BTN_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO BLOG_TAG_NAME (BTN_ID,BTN_CLASS,BTN_NAME) 
VALUES('BT'||LPAD(TO_CHAR(BTN_SEQ.NEXTVAL), 6, '0'),'亞洲','台灣');
INSERT INTO BLOG_TAG_NAME (BTN_ID,BTN_CLASS,BTN_NAME) 
VALUES('BT'||LPAD(TO_CHAR(BTN_SEQ.NEXTVAL), 6, '0'),'亞洲','日本');


INSERT INTO BLOG_TAG_NAME (BTN_ID,BTN_CLASS,BTN_NAME) 
VALUES('BT'||LPAD(TO_CHAR(BTN_SEQ.NEXTVAL), 6, '0'),'亞洲','韓國');


INSERT INTO BLOG_TAG_NAME (BTN_ID,BTN_CLASS,BTN_NAME) 
VALUES('BT'||LPAD(TO_CHAR(BTN_SEQ.NEXTVAL), 6, '0'),'亞洲','中國');


INSERT INTO BLOG_TAG_NAME (BTN_ID,BTN_CLASS,BTN_NAME) 
VALUES('BT'||LPAD(TO_CHAR(BTN_SEQ.NEXTVAL), 6, '0'),'亞洲','菲律賓');


--ATTRACTIONS 景點
DROP SEQUENCE ATT_SEQ;
CREATE SEQUENCE ATT_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO ATTRACTIONS (ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS,ATT_STATUS) VALUES ('A'||LPAD(TO_CHAR(ATT_SEQ.NEXTVAL), 9, '0'),'西門町',25.042603,121.507527,'台灣','西門町因為位於台北城的西門外，因此得名。在日治時代，西門町原本還只是一片荒涼的地方，後來日本人決定仿效東京淺草區，在此設立休閒商業區。其中最早的娛樂設施為1897年的台北座、1902年的榮座（現為新萬國商場）及1908年的八角堂（今西門紅樓）。新世界館（現為誠品116、真善美戲院）旁的街道，稱為「片倉通」，有許多日本料理店。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000001.jpg')),'台北市萬華區西門町',1);
INSERT INTO ATTRACTIONS (ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS,ATT_STATUS) VALUES ('A'||LPAD(TO_CHAR(ATT_SEQ.NEXTVAL), 9, '0'),'九份老街',25.107854,121.836218,'台灣','九份老街主要範圍以聚集在基山街、豎崎路及輕便路等街道為主，是全台灣最熱門的觀光景點之一，全年觀光客絡繹不絕。若以客源分析，平日以來自日本、韓國等地的外籍觀光客以及中國大陸、香港、澳門的遊客和本國遊客各占一半，假日則以國民旅遊為主，是北台灣國際級的觀光景點。商圈定位鮮明，集歷史、天然景致、美食文化於一爐。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000002.jpg')),'新北市瑞芳區九份',1);
INSERT INTO ATTRACTIONS (ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS,ATT_STATUS) VALUES ('A'||LPAD(TO_CHAR(ATT_SEQ.NEXTVAL), 9, '0'),'饒河街觀光夜市',25.050954,121.575336,'台灣','饒河街觀光夜市 （英語：RAOHE STREET NIGHT MARKET），又稱饒河街夜市、饒河夜市。街名源自合江省饒河縣（今屬黑龍江省），滿語意為「禽獸眾多之地」。位於臺灣臺北市松山區饒河街，為臺北市著名的觀光夜市之一，也是臺灣繼華西街觀光夜市後第二座觀光夜市。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000003.jpg')),'105台北市松山區饒河街',1);
INSERT INTO ATTRACTIONS (ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS,ATT_STATUS) VALUES ('A'||LPAD(TO_CHAR(ATT_SEQ.NEXTVAL), 9, '0'),'日月潭',23.852301,120.900942,'台灣','日月潭（邵語：ZINTUN；閩南語：JI?T-GOA?T-TH?M，英語：SUN MOON LAKE）位於臺灣南投縣魚池鄉日月村，為日潭與月潭之合稱，因其雙潭水色各異而得名。是臺灣島上第二大湖泊（僅次於曾文水庫）及第一大（半）天然湖泊兼發電水庫。湖面海拔736公尺，常態面積7.93平方公里（滿水位8.4平方公里），最大水深27公尺，自然生態豐富，但亦為最多外來種生物的淡水湖泊之一。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000004.jpg')),'555南投縣魚池鄉',1);
INSERT INTO ATTRACTIONS (ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS,ATT_STATUS) VALUES ('A'||LPAD(TO_CHAR(ATT_SEQ.NEXTVAL), 9, '0'),'清境農場',24.055347,121.157641,'台灣','清境農場位於台灣南投縣仁愛鄉，海拔約1700至2000公尺，為中華民國國軍退除役官兵輔導委員會所經營之公有事業。與武陵農場、梨山福壽山農場合稱為台灣三大高山農場。場址位於南投縣仁愛鄉大同村仁和路170號（台14甲線旁），清境農場地區飲食文化以滇緬料理聞名。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000005.jpg')),'546南投縣仁愛鄉仁和路170號',1);
INSERT INTO ATTRACTIONS (ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS,ATT_STATUS) VALUES ('A'||LPAD(TO_CHAR(ATT_SEQ.NEXTVAL), 9, '0'),'太魯閣國家公園',24.193926,121.488774,'台灣','太魯閣國家公園是台灣第四座成立的國家公園，前身為日治時期成立之次高太魯閣國立公園（1937-1945）。第二次世界大戰後為國家級風景區，1986年11月12日公告計畫，1986年11月28日成立管理處。位於台灣東部，地跨花蓮縣、臺中市、南投縣三個行政區。園內有台灣第一條東西橫貫公路通過，稱為中橫公路系統。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000006.jpg')),'花蓮縣秀林鄉富世村富世291號',1);
INSERT INTO ATTRACTIONS (ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS,ATT_STATUS) VALUES ('A'||LPAD(TO_CHAR(ATT_SEQ.NEXTVAL), 9, '0'),'墾丁國家公園',21.948330,120.777562,'台灣','墾丁國家公園是台灣在戰後時期第一個成立的國家公園，成立於1984年，隸屬內政部營建署，下設管理處。全境位於屏東縣、台灣本島最南端的恆春半島，陸地面積約18,084公頃，海域面積約15,206公頃，合計近33,290公頃，園區南北長約24公里，東西寬約24公里，全境屬熱帶，為臺灣熱門觀光勝地之一。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000007.jpg')),'屏東縣',1);
INSERT INTO ATTRACTIONS (ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS,ATT_STATUS) VALUES ('A'||LPAD(TO_CHAR(ATT_SEQ.NEXTVAL), 9, '0'),'玉山國家公園',23.469999,120.948700,'台灣','玉山國家公園是中華民國最早的國家公園之一，前身為日治時期成立之新高阿里山國立公園（1937–1945）。1985年4月6日公告計畫，1985年4月10日成立管理處，總面積103,121.4公頃，涵蓋台灣本島行政區域包括南投縣、嘉義縣、高雄市以及花蓮縣，為台灣陸域面積最大之國家公園。園區位居台灣本島中央地帶，地理位置獨特，奇峰兀立，雄偉壯麗，為台灣高山少數仍保存原始風貌之地區。其間包括有台灣第一高峰，海拔3952公尺之玉山主峰，主峰鄰近地區崇山峻嶺，溪谷深邃，天然植被隨海拔之變化而異，由亞熱帶、溫帶以至寒帶林相次變化，野生動物遍布，並具有清朝所建歷史遺跡八通關古道；因此，全區蘊藏許多珍貴之生態資源及人文史蹟。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000008.jpg')),'南投縣信義鄉',1);
INSERT INTO ATTRACTIONS (ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS,ATT_STATUS) VALUES ('A'||LPAD(TO_CHAR(ATT_SEQ.NEXTVAL), 9, '0'),'雪霸國家公園',24.362418,121.123024,'台灣','雪霸國家公園是臺灣第五座國家公園，可溯至日治時期成立之次高太魯閣國立公園，1991年3月1日公告計畫、1992年7月1日成立管理處，以雪山和大霸尖山的「雪」、「霸」兩字命名，這兩座山也是該公園主要的保護目標。其涵蓋範圍從北邊的樂山到邊吉岩山之稜線為界，到南邊的宇羅尾山和大甲溪中游，總面積共有76,850公頃，橫跨新竹縣、苗栗縣、臺中市等3縣市。公園內高山林立，峻秀壯觀，並有稀有的台灣寬尾鳳蝶，及瀕臨絕種的櫻花鉤吻鮭，是臺灣登山路線最多、最複雜的國家公園。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000009.jpg')),'新竹縣五峰鄉',1);
INSERT INTO ATTRACTIONS (ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS,ATT_STATUS) VALUES ('A'||LPAD(TO_CHAR(ATT_SEQ.NEXTVAL), 9, '0'),'金門國家公園',24.444165,118.350356,'台灣','金門國家公園位於金門縣，為中華民國第六座國家公園，1995年5月25日公告計畫，1995年10月18日成立管理處，是首座位於離島的國家公園，也是首座以維護歷史文化資產、戰役紀念為主，並兼具自然資源保育功能的國家公園。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000010.jpg')),'892金門縣金寧鄉伯玉路二段460號',1);




--AD
DROP SEQUENCE AD_SEQ;
CREATE SEQUENCE AD_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO AD(AD_ID,AD_TITLE,AD_TEXT,AD_LINK,AD_PIC,AD_STAT,CLICKCOUNT)
VALUES('AD'||LPAD(TO_CHAR(AD_SEQ.NEXTVAL), 6, '0'),
       '2018自然系行程 預購','網羅自然系美拍景點，搶先預約享早鳥優惠，暢遊瑞士馬特洪峰、奧地利鹽湖區、荷蘭鬱金香、美加國家公園深度之旅、純淨紐澳。',
       LOWER('HTTPS://WWW.EVERFUNTRAVEL.COM/PROMO/SPECIAL/2018-PRE-ORDER/'),
	   bfile_to_blob (BFILENAME ('IMAGE_AD_DIR','ad01.jpeg')),
       0,
       0);


INSERT INTO AD(AD_ID,AD_TITLE,AD_TEXT,AD_LINK,AD_PIC,AD_ACTADDTIME,AD_STAT,CLICKCOUNT)
VALUES('AD'||LPAD(TO_CHAR(AD_SEQ.NEXTVAL), 6, '0'),
       '泰國‧日本‧馬來西亞','賽事開跑，全球瘋狂！馬上預訂行程，食宿、交通、門票全備齊，讓你輕鬆出發泰國武里南、日本茂木、馬來西亞雪邦，朝聖熱血戰役！',
       LOWER('HTTPS://WWW.EVERFUNTRAVEL.COM/PROMO/SPECIAL/MOTOGP/'),
	   bfile_to_blob (BFILENAME ('IMAGE_AD_DIR','ad02.jpeg')),
       TO_TIMESTAMP('2018-07-11 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),
       1,
       0);


INSERT INTO AD(AD_ID,AD_TITLE,AD_TEXT,AD_LINK,AD_PIC,AD_STAT,CLICKCOUNT)
VALUES('AD'||LPAD(TO_CHAR(AD_SEQ.NEXTVAL), 6, '0'),
       '親子共遊提案','東南亞及島嶼的親子共遊提案，網羅ABCDE五大亮點，邀你一起FUN遊，透過旅行，豐富孩子視野，製造家庭的美好回憶。',
       LOWER('HTTPS://WWW.EVERFUNTRAVEL.COM/PROMO/SPECIAL/SUMMER-FAMILY-TOUR/'),
	   bfile_to_blob (BFILENAME ('IMAGE_AD_DIR','ad03.jpg')),
       0,
       0);


INSERT INTO AD(AD_ID,AD_TITLE,AD_TEXT,AD_LINK,AD_PIC,AD_ACTADDTIME,AD_STAT,CLICKCOUNT)
VALUES('AD'||LPAD(TO_CHAR(AD_SEQ.NEXTVAL), 6, '0'),
       '行程你設計 旅遊更有個性','玩轉全球主題樂園，提早選購景點門票、交通票券、一日遊等套票，不但行程安排更順利，還可以省下費用，旅程更輕鬆、盡興。',
       LOWER('HTTPS://WWW.EVERFUNTRAVEL.COM/PROMO/SPECIAL/FIT-THEME-PARK/'),
	   bfile_to_blob (BFILENAME ('IMAGE_AD_DIR','ad04.jpg')),
       TO_TIMESTAMP('2018-07-17 20:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),
       1,
       0);

INSERT INTO AD(AD_ID,AD_TITLE,AD_TEXT,AD_LINK,AD_PIC,AD_ACTADDTIME,AD_STAT,CLICKCOUNT)
VALUES('AD'||LPAD(TO_CHAR(AD_SEQ.NEXTVAL), 6, '0'),
       '團體旅遊下殺萬元有找','環遊世界不再是夢想 ! 規劃今年9月-明年4月出發的精采假期，團體旅遊萬元有找，最多折$5,000，超級激省下殺，讓您輕鬆玩遍全世界。',
       LOWER('https://www.liontravel.com/promotion/travelfair/summer/?sprima=defneM3H05'),
	   bfile_to_blob (BFILENAME ('IMAGE_AD_DIR','ad05.jpg')),
       TO_TIMESTAMP('2018-07-19 03:34:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),
       1,
       0);

INSERT INTO AD(AD_ID,AD_TITLE,AD_TEXT,AD_LINK,AD_PIC,AD_ACTADDTIME,AD_STAT,CLICKCOUNT)
VALUES('AD'||LPAD(TO_CHAR(AD_SEQ.NEXTVAL), 6, '0'),
       '華航★說好的旅行','說好的旅行 今年一定要出發！優惠開票日期：2018/07/06 ~ 2018/07/27。出發日期：限台北出發，各航線適用出發日皆不同，請以訂購頁面為主。',
       LOWER('https://www.liontravel.com/promotion/airline/chinaairlines/itf.html?sprima=defneM3H05'),
	   bfile_to_blob (BFILENAME ('IMAGE_AD_DIR','ad06.jpg')),
       TO_TIMESTAMP('2018-07-19 03:34:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),
       1,
       0);
	   
INSERT INTO AD(AD_ID,AD_TITLE,AD_TEXT,AD_LINK,AD_PIC,AD_STAT,CLICKCOUNT)
VALUES('AD'||LPAD(TO_CHAR(AD_SEQ.NEXTVAL), 6, '0'),
       '賞紅葉享美食品美酒','人生就是一次旅行，在乎的是沿途的風景和看景的心情。而秋天是一年當中最美最適合出遊的季節，期待在旅途中遇見美麗的人事物，帶回更炫麗的未來',
       LOWER('https://www.liontravel.com/promotion/season/autumntravel/?sprima=defneM3H05'),
	   bfile_to_blob (BFILENAME ('IMAGE_AD_DIR','ad07.jpg')),
       0,
       0);


--PHOTO_TAG
DROP SEQUENCE PHOTO_TAG_SEQ;
CREATE SEQUENCE PHOTO_TAG_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE;


INSERT INTO PHOTO_TAG (PHOTO_TAG_NO,TAG_CONTENT) VALUES ('PTN'||LPAD(TO_CHAR(PHOTO_TAG_SEQ.NEXTVAL), 6, '0'),'台北');
INSERT INTO PHOTO_TAG (PHOTO_TAG_NO,TAG_CONTENT) VALUES ('PTN'||LPAD(TO_CHAR(PHOTO_TAG_SEQ.NEXTVAL), 6, '0'),'台中');
INSERT INTO PHOTO_TAG (PHOTO_TAG_NO,TAG_CONTENT) VALUES ('PTN'||LPAD(TO_CHAR(PHOTO_TAG_SEQ.NEXTVAL), 6, '0'),'台南');
INSERT INTO PHOTO_TAG (PHOTO_TAG_NO,TAG_CONTENT) VALUES ('PTN'||LPAD(TO_CHAR(PHOTO_TAG_SEQ.NEXTVAL), 6, '0'),'高雄');
INSERT INTO PHOTO_TAG (PHOTO_TAG_NO,TAG_CONTENT) VALUES ('PTN'||LPAD(TO_CHAR(PHOTO_TAG_SEQ.NEXTVAL), 6, '0'),'大阪');




--ADMIN
DROP SEQUENCE ADMIN_SEQ;
CREATE SEQUENCE ADMIN_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE;


INSERT INTO ADMIN (ADMIN_ID,ADMIN_ACCOUNT,ADMIN_PASSWORD,ADMIN_NAME,ADMIN_MAIL,ADMIN_PHONE) 
VALUES ('ADMIN'||LPAD(TO_CHAR(ADMIN_SEQ.NEXTVAL), 3, '0'),'AAA123','123456','李柴柴','LEE123@GMAIL.COM','0912345678');


INSERT INTO ADMIN (ADMIN_ID,ADMIN_ACCOUNT,ADMIN_PASSWORD,ADMIN_NAME,ADMIN_MAIL,ADMIN_PHONE) 
VALUES ('ADMIN'||LPAD(TO_CHAR(ADMIN_SEQ.NEXTVAL), 3, '0'),'AAA456','123456','林宗宗','LIN456@GMAIL.COM','0912345678');


INSERT INTO ADMIN (ADMIN_ID,ADMIN_ACCOUNT,ADMIN_PASSWORD,ADMIN_NAME,ADMIN_MAIL,ADMIN_PHONE) 
VALUES ('ADMIN'||LPAD(TO_CHAR(ADMIN_SEQ.NEXTVAL), 3, '0'),'AAA789','123456','賴旺旺','LIE789@GMAIL.COM','0912345678');


INSERT INTO ADMIN (ADMIN_ID,ADMIN_ACCOUNT,ADMIN_PASSWORD,ADMIN_NAME,ADMIN_MAIL,ADMIN_PHONE) 
VALUES ('ADMIN'||LPAD(TO_CHAR(ADMIN_SEQ.NEXTVAL), 3, '0'),'AAA1234','123456','二哈哈','HAHA123@GMAIL.COM','0912345678');


INSERT INTO ADMIN (ADMIN_ID,ADMIN_ACCOUNT,ADMIN_PASSWORD,ADMIN_NAME,ADMIN_MAIL,ADMIN_PHONE) 
VALUES ('ADMIN'||LPAD(TO_CHAR(ADMIN_SEQ.NEXTVAL), 3, '0'),'AAA12345','123456','腸寶寶','BOBO123@GMAIL.COM','0912345678');






--STORE_711_CITY
--超商取貨城市
DROP SEQUENCE STORE_CITY_SEQ;
CREATE SEQUENCE STORE_CITY_SEQ
INCREMENT BY 1
START WITH 10
NOMAXVALUE
NOCYCLE
NOCACHE;




INSERT INTO STORE_711_CITY (STORE_711_CITY_ID,STORE_711_CITY_NAME) VALUES (STORE_CITY_SEQ.NEXTVAL,'台北市');
INSERT INTO STORE_711_CITY (STORE_711_CITY_ID,STORE_711_CITY_NAME) VALUES (STORE_CITY_SEQ.NEXTVAL,'新北市');
INSERT INTO STORE_711_CITY (STORE_711_CITY_ID,STORE_711_CITY_NAME) VALUES (STORE_CITY_SEQ.NEXTVAL,'基隆市');




--STORE_711_DIST
--超商取貨行政區
DROP SEQUENCE STORE_DIST_SEQ;
CREATE SEQUENCE STORE_DIST_SEQ
INCREMENT BY 1
START WITH 100
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO STORE_711_DIST ( STORE_711_DIST_ID,STORE_711_CITY_ID,STORE_711_DIST_NAME) VALUES (STORE_DIST_SEQ.NEXTVAL,10,'中正區');
INSERT INTO STORE_711_DIST ( STORE_711_DIST_ID,STORE_711_CITY_ID,STORE_711_DIST_NAME) VALUES (STORE_DIST_SEQ.NEXTVAL,10,'大同區');
INSERT INTO STORE_711_DIST ( STORE_711_DIST_ID,STORE_711_CITY_ID,STORE_711_DIST_NAME) VALUES (STORE_DIST_SEQ.NEXTVAL,10,'中山區');
INSERT INTO STORE_711_DIST ( STORE_711_DIST_ID,STORE_711_CITY_ID,STORE_711_DIST_NAME) VALUES (STORE_DIST_SEQ.NEXTVAL,10,'大安區');


--ABOUT_US
DROP SEQUENCE ABOUT_US_SEQ ;
CREATE SEQUENCE ABOUT_US_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO ABOUT_US (ABOUT_US_ID,ABOUT_CONTENT) VALUES ('AB'||LPAD(TO_CHAR(ABOUT_US_SEQ.NEXTVAL), 9, '0'),' ');
--STORE_711
--超商取貨
DROP TABLE STORE_711 CASCADE CONSTRAINTS;
CREATE TABLE STORE_711 (
 STORE_711_ID NUMBER(10,0)  NOT NULL,
 STORE_711_DIST_ID NUMBER(10,0)  NOT NULL,
 STORE_711_NAME VARCHAR2(100)  NOT NULL,
 STORE_711_ADDR VARCHAR2(300)  NOT NULL,
 STORE_711_CITY_NAME VARCHAR2(100)  NOT NULL,
 STORE_711_DIST_NAME VARCHAR2(100)  NOT NULL
);


ALTER TABLE STORE_711 ADD CONSTRAINT PK_STORE_711 PRIMARY KEY (STORE_711_ID);


INSERT INTO STORE_711 (STORE_711_ID,STORE_711_DIST_ID,STORE_711_NAME,STORE_711_ADDR,STORE_711_CITY_NAME,STORE_711_DIST_NAME) VALUES (110242,101,'敦維','台北市大安區東豐街43號45號1樓','台北市','大安區');
INSERT INTO STORE_711 (STORE_711_ID,STORE_711_DIST_ID,STORE_711_NAME,STORE_711_ADDR,STORE_711_CITY_NAME,STORE_711_DIST_NAME) VALUES (110334,101,'安信','台北市大安區信義路四段74號1樓','台北市','大安區');
INSERT INTO STORE_711 (STORE_711_ID,STORE_711_DIST_ID,STORE_711_NAME,STORE_711_ADDR,STORE_711_CITY_NAME,STORE_711_DIST_NAME) VALUES (110448,102,'古亭','台北市中正區汀州路二段210號','台北市','中正區');
--MEMBER
DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO MEMBER (MEM_ID,MEM_ACCOUNT,MEM_PASSWORD,MEM_NAME,MEM_SEX,MEM_ADDRESS,MEM_BIRTHDAY,MEM_PHONE,MEM_PROFILE,MEM_PHOTO,MEM_STATE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,DELIVERY_ADDRESS_3,STORE_NO_1,STORE_NO_2,STORE_NO_3,STORE_ADDR_1,STORE_ADDR_2,STORE_ADDR_3,STORE_NAME_1,STORE_NAME_2,STORE_NAME_3) 
VALUES ('M'||LPAD(TO_CHAR(MEMBER_SEQ.NEXTVAL), 6, '0'),'TORRES123@GMAIL.COM','123456','李柴柴','1','台北市-信義區-市府路1號',TO_DATE('2008-05-18','YYYY-MM-DD'),'0988888888','我是誰',
bfile_to_blob (BFILENAME ('IMAGE_MEMBER_DIR','142447.jpg'))
,'1','台北市-信義區-市府路2號',NULL,NULL,'111',NULL,NULL,'台北市-信義區-市府路3號',NULL,NULL,'信義101店',NULL,NULL);


INSERT INTO MEMBER (MEM_ID,MEM_ACCOUNT,MEM_PASSWORD,MEM_NAME,MEM_SEX,MEM_ADDRESS,MEM_BIRTHDAY,MEM_PHONE,MEM_PROFILE,MEM_PHOTO,MEM_STATE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,DELIVERY_ADDRESS_3,STORE_NO_1,STORE_NO_2,STORE_NO_3,STORE_ADDR_1,STORE_ADDR_2,STORE_ADDR_3,STORE_NAME_1,STORE_NAME_2,STORE_NAME_3) 
VALUES ('M'||LPAD(TO_CHAR(MEMBER_SEQ.NEXTVAL), 6, '0'),'LINHAHA666@YAHOO.COM.TW','123456','林宗宗','1','桃園市-中壢區-中大路200號',TO_DATE('2013-07-02','YYYY-MM-DD'),'0933333333','我是誰',
bfile_to_blob (BFILENAME ('IMAGE_MEMBER_DIR','haha.jpg'))
,'0','桃園市-中壢區-中大路100號-1','桃園市-中壢區-中大路200號-2',NULL,'111','222',NULL,'桃園市-中壢區-中大路666號-1','桃園市-中壢區-中大路666號-2',NULL,'隆凱店','中大店',NULL);


INSERT INTO MEMBER (MEM_ID,MEM_ACCOUNT,MEM_PASSWORD,MEM_NAME,MEM_SEX,MEM_ADDRESS,MEM_BIRTHDAY,MEM_PHONE,MEM_PROFILE,MEM_PHOTO,MEM_STATE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,DELIVERY_ADDRESS_3,STORE_NO_1,STORE_NO_2,STORE_NO_3,STORE_ADDR_1,STORE_ADDR_2,STORE_ADDR_3,STORE_NAME_1,STORE_NAME_2,STORE_NAME_3) 
VALUES ('M'||LPAD(TO_CHAR(MEMBER_SEQ.NEXTVAL), 6, '0'),'WOWOLIE5566@HOTMAIL.COM.TW','123456','賴旺旺','1','桃園市-中壢區-宵夜街123號',TO_DATE('2018-08-26','YYYY-MM-DD'),'0977678999','我是誰',
bfile_to_blob (BFILENAME ('IMAGE_MEMBER_DIR','wowo.jpg'))
,'1','桃園市-中壢區-宵夜街150號-1','桃園市-中壢區-中大路299號-3','桃園市-中壢區-中大路200號-3','111','222','333','桃園市-中壢區-中大路333號-1','桃園市-中壢區-中大路666號-2','桃園市-中壢區-中大路666號-3','學央店','中大店','中大2店');


INSERT INTO MEMBER (MEM_ID,MEM_ACCOUNT,MEM_PASSWORD,MEM_NAME,MEM_SEX,MEM_ADDRESS,MEM_BIRTHDAY,MEM_PHONE,MEM_PROFILE,MEM_PHOTO,MEM_STATE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,DELIVERY_ADDRESS_3,STORE_NO_1,STORE_NO_2,STORE_NO_3,STORE_ADDR_1,STORE_ADDR_2,STORE_ADDR_3,STORE_NAME_1,STORE_NAME_2,STORE_NAME_3) 
VALUES ('M'||LPAD(TO_CHAR(MEMBER_SEQ.NEXTVAL), 6, '0'),'CHUSHI1122@GMAIL.COM','123456','朱小修','1','桃園市-中壢區-隨緣巷-43號',TO_DATE('2015-04-14','YYYY-MM-DD'),'0977678999','我是誰',
bfile_to_blob (BFILENAME ('IMAGE_MEMBER_DIR','chai2.jpg'))
,'1','桃園市-中壢區-宵夜街250號-1','桃園市-中壢區-中大路399號-4','桃園市-中壢區-中大路200號-3','666','777','888','桃園市-中壢區-中大路333號-1','桃園市-中壢區-中大路666號-2','桃園市-中壢區-中大路676號-3','學央店','中大店','中大7店');


INSERT INTO MEMBER (MEM_ID,MEM_ACCOUNT,MEM_PASSWORD,MEM_NAME,MEM_SEX,MEM_ADDRESS,MEM_BIRTHDAY,MEM_PHONE,MEM_PROFILE,MEM_PHOTO,MEM_STATE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,STORE_NO_1,STORE_NO_2,STORE_ADDR_1,STORE_ADDR_2,STORE_NAME_1,STORE_NAME_2) 
VALUES ('M'||LPAD(TO_CHAR(MEMBER_SEQ.NEXTVAL), 6, '0'),'OLDBROTHER123456@HOTMAIL.COM','123456','老大哥','1','桃園市-中壢區-大帝路50號',TO_DATE('2018-11-26','YYYY-MM-DD'),'0977668991','HELLO MY NAME IS 老大哥'
,bfile_to_blob (BFILENAME ('IMAGE_MEMBER_DIR','golddog.jpg'))
,'1','桃園市-中壢區-宵夜街300號-1','桃園市-中壢區-中大路499號-5','123','456','桃園市-中壢區-中大路333號-1','桃園市-中壢區-中大路666號-2','學央店','中大店');


INSERT INTO MEMBER (MEM_ID,MEM_ACCOUNT,MEM_PASSWORD,MEM_NAME,MEM_SEX,MEM_ADDRESS,MEM_BIRTHDAY,MEM_PHONE,MEM_PROFILE,MEM_PHOTO,MEM_STATE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,DELIVERY_ADDRESS_3,STORE_NO_1,STORE_NO_2,STORE_NO_3,STORE_ADDR_1,STORE_ADDR_2,STORE_ADDR_3,STORE_NAME_1,STORE_NAME_2,STORE_NAME_3) 
VALUES ('M'||LPAD(TO_CHAR(MEMBER_SEQ.NEXTVAL), 6, '0'),'SISTER123@HOTMAIL.COM','123456','小姊姊','2','桃園市-中壢區-蘭苑路9號-2',TO_DATE('2018-10-03','YYYY-MM-DD'),'0977678999','安安我是小番茄'
,bfile_to_blob (BFILENAME ('IMAGE_MEMBER_DIR','orange_cat.jpg'))
,'1','桃園市-中壢區-宵夜街300號-1','桃園市-中壢區-中大路499號-5','桃園市-中壢區-中大路200號-3','123','456','789','桃園市-中壢區-中大路333號-1','桃園市-中壢區-中大路666號-2','桃園市-中壢區-中大路666號-5','學央店','中大店','中大5店');


INSERT INTO MEMBER (MEM_ID,MEM_ACCOUNT,MEM_PASSWORD,MEM_NAME,MEM_SEX,MEM_ADDRESS,MEM_BIRTHDAY,MEM_PHONE,MEM_PROFILE,MEM_PHOTO,MEM_STATE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,STORE_NO_1,STORE_NO_2,STORE_ADDR_1,STORE_ADDR_2,STORE_NAME_1,STORE_NAME_2) 
VALUES ('M'||LPAD(TO_CHAR(MEMBER_SEQ.NEXTVAL), 6, '0'),'BROTHER123@HOTMAIL.COM','123456','小哥哥','3','桃園市-中壢區-蘭苑路9號-2',TO_DATE('2018-11-26','YYYY-MM-DD'),'0977668991','安安我是神雕'
,bfile_to_blob (BFILENAME ('IMAGE_MEMBER_DIR','Standing_cat.jpg'))
,'1','桃園市-中壢區-宵夜街300號-1','桃園市-中壢區-中大路499號-5','123','456','桃園市-中壢區-中大路333號-1','桃園市-中壢區-中大路666號-2','學央店','中大店');


INSERT INTO MEMBER (MEM_ID,MEM_ACCOUNT,MEM_PASSWORD,MEM_NAME,MEM_SEX,MEM_ADDRESS,MEM_BIRTHDAY,MEM_PHONE,MEM_PROFILE,MEM_PHOTO,MEM_STATE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,STORE_NO_1,STORE_NO_2,STORE_ADDR_1,STORE_ADDR_2,STORE_NAME_1,STORE_NAME_2) 
VALUES ('M'||LPAD(TO_CHAR(MEMBER_SEQ.NEXTVAL), 6, '0'),'BROTHER123@HOTMAIL.COM','123456','丹丹','3','桃園市-中壢區-蘭苑路9號-2',TO_DATE('2018-11-26','YYYY-MM-DD'),'0977668991','安安我是丹丹'
,bfile_to_blob (BFILENAME ('IMAGE_MEMBER_DIR','142447.jpg'))
,'1','桃園市-中壢區-宵夜街300號-1','桃園市-中壢區-中大路499號-5','123','456','桃園市-中壢區-中大路333號-1','桃園市-中壢區-中大路666號-2','學央店','中大店');


INSERT INTO MEMBER (MEM_ID,MEM_ACCOUNT,MEM_PASSWORD,MEM_NAME,MEM_SEX,MEM_ADDRESS,MEM_BIRTHDAY,MEM_PHONE,MEM_PROFILE,MEM_PHOTO,MEM_STATE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,STORE_NO_1,STORE_NO_2,STORE_ADDR_1,STORE_ADDR_2,STORE_NAME_1,STORE_NAME_2) 
VALUES ('M'||LPAD(TO_CHAR(MEMBER_SEQ.NEXTVAL), 6, '0'),'PEN123@HOTMAIL.COM','123456','品儒','1','桃園市-中壢區-蘭苑路9號-1',TO_DATE('2018-11-26','YYYY-MM-DD'),'0977668991','安安我是品儒'
,bfile_to_blob (BFILENAME ('IMAGE_MEMBER_DIR','fairdog2.jpg'))
,'3','桃園市-中壢區-宵夜街300號-1','桃園市-中壢區-中大路499號-5','123','456','桃園市-中壢區-中大路333號-1','桃園市-中壢區-中大路666號-2','學央店','中大店');


INSERT INTO MEMBER (MEM_ID,MEM_ACCOUNT,MEM_PASSWORD,MEM_NAME,MEM_SEX,MEM_ADDRESS,MEM_BIRTHDAY,MEM_PHONE,MEM_PROFILE,MEM_PHOTO,MEM_STATE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,STORE_NO_1,STORE_NO_2,STORE_ADDR_1,STORE_ADDR_2,STORE_NAME_1,STORE_NAME_2) 
VALUES ('M'||LPAD(TO_CHAR(MEMBER_SEQ.NEXTVAL), 6, '0'),'PEN123@HOTMAIL.COM','123456','華霖','1','桃園市-中壢區-蘭苑路9號-1',TO_DATE('2018-11-26','YYYY-MM-DD'),'0977668991','安安我是華霖'
,bfile_to_blob (BFILENAME ('IMAGE_MEMBER_DIR','fairdog.jpg'))
,'3','桃園市-中壢區-宵夜街300號-1','桃園市-中壢區-中大路499號-5','123','456','桃園市-中壢區-中大路333號-1','桃園市-中壢區-中大路666號-2','學央店','中大店');


-- CHATROOM
DROP SEQUENCE CHATROOM_SEQ;
CREATE SEQUENCE CHATROOM_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
INSERT INTO CHATROOM(CHATROOM_ID,CHATROOM_NAME,CHATREC)
VALUES('CR'||LPAD(TO_CHAR(CHATROOM_SEQ.NEXTVAL), 6, '0'),
       '李柴柴與賴旺旺的對話',
       '[{"MEM_ID":"M000001","MSG":"哈囉賴旺~~~"},{"MEM_ID":"M000003","MSG":"HELLO,LEE!YOU SO CUTE!"}]');
INSERT INTO CHATROOM_JOIN(CHATROOM_ID,JOIN_MEMID)
VALUES('CR'||LPAD(TO_CHAR(CHATROOM_SEQ.CURRVAL), 6, '0'),'M000001');       
INSERT INTO CHATROOM_JOIN(CHATROOM_ID,JOIN_MEMID)
VALUES('CR'||LPAD(TO_CHAR(CHATROOM_SEQ.CURRVAL), 6, '0'),'M000003');    




INSERT INTO CHATROOM(CHATROOM_ID,CHATROOM_NAME,CHATREC)
VALUES('CR'||LPAD(TO_CHAR(CHATROOM_SEQ.NEXTVAL), 6, '0'),
       '林宗宗與賴旺旺的對話',
       '[{"MEM_ID":"M000002","MSG":"哈囉賴旺~~~"},{"MEM_ID":"M000003","MSG":"HELLO,LEE!YOU SO CUTE!"}]');
INSERT INTO CHATROOM_JOIN(CHATROOM_ID,JOIN_MEMID)
VALUES('CR'||LPAD(TO_CHAR(CHATROOM_SEQ.CURRVAL), 6, '0'),'M000002');       
INSERT INTO CHATROOM_JOIN(CHATROOM_ID,JOIN_MEMID)
VALUES('CR'||LPAD(TO_CHAR(CHATROOM_SEQ.CURRVAL), 6, '0'),'M000003'); 


--但李柴柴已封鎖朱小修
INSERT INTO CHATROOM(CHATROOM_ID,CHATROOM_NAME,CHATREC)
VALUES('CR'||LPAD(TO_CHAR(CHATROOM_SEQ.NEXTVAL), 6, '0'),
       '李柴柴與朱小修的對話',
       '[{"MEM_ID":"M000004","MSG":"哈囉myFriend~~~"},{"MEM_ID":"M000001","MSG":"爽啦"}]');
INSERT INTO CHATROOM_JOIN(CHATROOM_ID,JOIN_MEMID)
VALUES('CR'||LPAD(TO_CHAR(CHATROOM_SEQ.CURRVAL), 6, '0'),'M000004');       
INSERT INTO CHATROOM_JOIN(CHATROOM_ID,JOIN_MEMID)
VALUES('CR'||LPAD(TO_CHAR(CHATROOM_SEQ.CURRVAL), 6, '0'),'M000001');


-- PRODUCT
--商品
DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ
INCREMENT BY 1
START WITH 1001
NOMAXVALUE
NOCYCLE
NOCACHE;


Insert into PRODUCT (PRODUCT_ID,PRODUCT_CATEGORY_ID,PRODUCT_MEM_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESCR,PRODUCT_STOCK,PRODUCT_STATUS,PRODUCT_DATE,PRODUCT_PHOTO_1,PRODUCT_PHOTO_2,PRODUCT_PHOTO_3) values (product_seq.NEXTVAL,20,'M000001','越南 Vietnamobile電信30日上網卡~每日4GB流量後降速',200,'【卡片說明】：1.電信商：Vietnamobile；2.流量：3G網速，30天 每日4gb流量+20000越南盾話費；每日過4GB流量會停止使用，隔日凌晨12點後恢復正常。3.啟動使用方法：到達越南境內，插卡重新啟動手機使用。4. 電話號碼： 於右上方貼紙 018 開頭11位數字，可以撥接當地電話。',2,1,CURRENT_TIMESTAMP,bfile_to_blob (BFILENAME ('IMAGE_PRODUCT_DIR','prod1_1.jpg')),bfile_to_blob (BFILENAME ('IMAGE_PRODUCT_DIR','prod1_2.jpg')),bfile_to_blob (BFILENAME ('IMAGE_PRODUCT_DIR','prod1_3.jpg')));


Insert into PRODUCT (PRODUCT_ID,PRODUCT_CATEGORY_ID,PRODUCT_MEM_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESCR,PRODUCT_STOCK,PRODUCT_STATUS,PRODUCT_DATE,PRODUCT_PHOTO_1,PRODUCT_PHOTO_2) values (product_seq.NEXTVAL,20,'M000002','【大和無限卡】7天 4G吃到飽不降速 即插即用免設定 DOCOMO 日本上網卡',490,' 開通有效期限至2018/11/30號 ，一抵達可立即使用，每日無流量限制，全程4G高速上網，用完即丟免還卡，最長可用7日。'   
,5,1,TO_TIMESTAMP('12-06-18 10.31.19 ', 'DD-MM-YY HH.MI.SS '),bfile_to_blob (BFILENAME ('IMAGE_PRODUCT_DIR','prod2_1.jpg')),bfile_to_blob (BFILENAME ('IMAGE_PRODUCT_DIR','prod2_2.jpg')));


Insert into PRODUCT (PRODUCT_ID,PRODUCT_CATEGORY_ID,PRODUCT_MEM_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESCR,PRODUCT_STOCK,PRODUCT_STATUS,PRODUCT_DATE,PRODUCT_PHOTO_1,PRODUCT_PHOTO_2,PRODUCT_PHOTO_3,PRODUCT_PHOTO_4,PRODUCT_PHOTO_5) values (product_seq.NEXTVAL,10,'M000003','JR 關西鐵路周遊券 - 實體票',1600,'◆ 使用效期：自 購買票券日 起 3個月內 (有效期限內前至日本蓋章，並開始使用)
    日幣售價 1日- JPY2,200
                   2日- JPY4,300
                   3日- JPY5,300
                   4日- JPY6,300
◆ 使用範圍：從關西機場前往大阪、京都、神戶、奈良、姬路，不限次數搭乘關西機場快車（快速）「HARUKA號」及快車（快速）・當地列車（普通列車）的普通車廂非指定座席（普通車自由席）。
    *2017/4/10起適用西日本JR巴士。
    *可利用以下列車：
       (1)關西機場特快HARUKA號的普通車車廂非指座席(普通車自由席)。
       (2).JR西日本在來線的新快車(新快速)、快車(快速)、當地列車(普通列車)。
            - 普通車廂指定座席(普通車指定席)有需要另加超特急券。
            - 關西機場特快HARUKA號以外的超特急列車(特急列車)有需要另加超特急券。
            - 不能使用於新幹線。
    *無法搭乘以下列車
         - 新幹線和「HARUKA號」之外的超特急列車（特急列車）無法使用。
',3,1,TO_TIMESTAMP('04-07-18 08.21.19 ', 'DD-MM-YY HH.MI.SS '),bfile_to_blob (BFILENAME ('IMAGE_PRODUCT_DIR','prod3_1.jpg')),bfile_to_blob (BFILENAME ('IMAGE_PRODUCT_DIR','prod3_2.jpg')),bfile_to_blob (BFILENAME ('IMAGE_PRODUCT_DIR','prod3_3.jpg')),bfile_to_blob (BFILENAME ('IMAGE_PRODUCT_DIR','prod3_4.jpg')),bfile_to_blob (BFILENAME ('IMAGE_PRODUCT_DIR','prod3_5.jpg')));






--QUESTION
DROP SEQUENCE QUESTION_SEQ;
CREATE SEQUENCE QUESTION_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO QUESTION (QUESTION_ID,MEM_ID,QUESTION_CONTENT,BUILD_DATE) VALUES ('QU'||LPAD(TO_CHAR(QUESTION_SEQ.NEXTVAL), 9, '0'),'M000001',' ',TO_DATE('2018-07-21','YYYY-MM-DD'));
INSERT INTO QUESTION (QUESTION_ID,MEM_ID,QUESTION_CONTENT,BUILD_DATE) VALUES ('QU'||LPAD(TO_CHAR(QUESTION_SEQ.NEXTVAL), 9, '0'),'M000002',' ',TO_DATE('2018-07-22','YYYY-MM-DD'));
INSERT INTO QUESTION (QUESTION_ID,MEM_ID,QUESTION_CONTENT,BUILD_DATE) VALUES ('QU'||LPAD(TO_CHAR(QUESTION_SEQ.NEXTVAL), 9, '0'),'M000003',' ',TO_DATE('2018-07-23','YYYY-MM-DD'));




--QA_REPLY
DROP SEQUENCE QA_REPLY_SEQ;
CREATE SEQUENCE QA_REPLY_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO QA_REPLY (REPLY_ID,QUESTION_ID,MEM_ID,REPLY_CONTENT,REPLY_DATE) VALUES ('RE'||LPAD(TO_CHAR(QA_REPLY_SEQ.NEXTVAL), 9, '0'),'QU000000001','M000001',' ',TO_DATE('2018-07-21','YYYY-MM-DD'));
INSERT INTO QA_REPLY (REPLY_ID,QUESTION_ID,MEM_ID,REPLY_CONTENT,REPLY_DATE) VALUES ('RE'||LPAD(TO_CHAR(QA_REPLY_SEQ.NEXTVAL), 9, '0'),'QU000000002','M000002',' ',TO_DATE('2018-07-22','YYYY-MM-DD'));
INSERT INTO QA_REPLY (REPLY_ID,QUESTION_ID,MEM_ID,REPLY_CONTENT,REPLY_DATE) VALUES ('RE'||LPAD(TO_CHAR(QA_REPLY_SEQ.NEXTVAL), 9, '0'),'QU000000003','M000003',' ',TO_DATE('2018-07-23','YYYY-MM-DD'));




--FRIEND
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
INSERT INTO FRIEND(FRI_ID,MEMID_SELF,MEMID_FRI,FRI_STAT)
VALUES('FRI'||LPAD(TO_CHAR(FRIEND_SEQ.NEXTVAL), 6, '0'),
       'M000001',
       'M000002',
       1);
INSERT INTO FRIEND(FRI_ID,MEMID_SELF,MEMID_FRI,FRI_TIME,FRI_STAT)
VALUES('FRI'||LPAD(TO_CHAR(FRIEND_SEQ.NEXTVAL), 6, '0'),
       'M000001',
       'M000003',
       TO_TIMESTAMP('2018-07-11 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),
       2);
INSERT INTO FRIEND(FRI_ID,MEMID_SELF,MEMID_FRI,FRI_TIME,FRI_STAT)
VALUES('FRI'||LPAD(TO_CHAR(FRIEND_SEQ.NEXTVAL), 6, '0'),
       'M000001',
       'M000004',
       TO_TIMESTAMP('2018-05-02 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),
       3);
INSERT INTO FRIEND(FRI_ID,MEMID_SELF,MEMID_FRI,FRI_TIME,FRI_STAT)
VALUES('FRI'||LPAD(TO_CHAR(FRIEND_SEQ.NEXTVAL), 6, '0'),
       'M000002',
       'M000003',
       TO_TIMESTAMP('2018-07-15 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),
       2);
INSERT INTO FRIEND(FRI_ID,MEMID_SELF,MEMID_FRI,FRI_TIME,FRI_STAT)
VALUES('FRI'||LPAD(TO_CHAR(FRIEND_SEQ.NEXTVAL), 6, '0'),
       'M000003',
       'M000002',
       TO_TIMESTAMP('2018-07-15 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),
       2);
INSERT INTO FRIEND(FRI_ID,MEMID_SELF,MEMID_FRI,FRI_TIME,FRI_STAT)
VALUES('FRI'||LPAD(TO_CHAR(FRIEND_SEQ.NEXTVAL), 6, '0'),
       'M000003',
       'M000001',
       TO_TIMESTAMP('2018-07-11 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),
       2);


INSERT INTO FRIEND(FRI_ID,MEMID_SELF,MEMID_FRI,FRI_TIME,FRI_STAT)
VALUES('FRI'||LPAD(TO_CHAR(FRIEND_SEQ.NEXTVAL), 6, '0'),
       'M000004',
       'M000001',
       TO_TIMESTAMP('2018-05-02 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),
       2);
      




-- PRODUCT_WISHLIST
--收藏商品
DROP TABLE PRODUCT_WISHLIST CASCADE CONSTRAINTS;
CREATE TABLE PRODUCT_WISHLIST (
 WISHLIST_PRODUCT_ID NUMBER(10,0)  NOT NULL,
 WISHLIST_MEM_ID VARCHAR2(20) NOT NULL,
 PRODUCT_WISHLIST_TIME TIMESTAMP
);


ALTER TABLE PRODUCT_WISHLIST ADD CONSTRAINT PK_PRODUCT_WISHLIST PRIMARY KEY (WISHLIST_PRODUCT_ID,WISHLIST_MEM_ID);




INSERT INTO PRODUCT_WISHLIST (WISHLIST_PRODUCT_ID,WISHLIST_MEM_ID,PRODUCT_WISHLIST_TIME) VALUES (1001,'M000001',CURRENT_TIMESTAMP);
INSERT INTO PRODUCT_WISHLIST (WISHLIST_PRODUCT_ID,WISHLIST_MEM_ID,PRODUCT_WISHLIST_TIME) VALUES (1008,'M000002',CURRENT_TIMESTAMP);
INSERT INTO PRODUCT_WISHLIST (WISHLIST_PRODUCT_ID,WISHLIST_MEM_ID,PRODUCT_WISHLIST_TIME) VALUES (1010,'M000003',CURRENT_TIMESTAMP);




--QA_COLLECT
DROP SEQUENCE QA_COLLECT_SEQ;
CREATE SEQUENCE QA_COLLECT_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO QA_COLLECT (QUESTION_ID,MEM_ID) VALUES ('QU000000001','M000001');
INSERT INTO QA_COLLECT (QUESTION_ID,MEM_ID) VALUES ('QU000000002','M000002');
INSERT INTO QA_COLLECT (QUESTION_ID,MEM_ID) VALUES ('QU000000003','M000003');






--PRODUCT_REPORT
--檢舉商品
DROP TABLE PRODUCT_REPORT CASCADE CONSTRAINTS;
CREATE TABLE PRODUCT_REPORT (
 PROD_REPORT_PRODUCT_ID NUMBER(10,0)  NOT NULL,
 PROD_REPORT_MEM_ID VARCHAR2(20) NOT NULL,
 PROD_REPORT_REASON VARCHAR2(300) NOT NULL,
 PROD_REPORT_TIME TIMESTAMP,
 PROD_REPORT_STATUS NUMBER(1,0)
);


ALTER TABLE PRODUCT_REPORT ADD CONSTRAINT PK_PRODUCT_REPORT PRIMARY KEY (PROD_REPORT_PRODUCT_ID,PROD_REPORT_MEM_ID);


INSERT INTO PRODUCT_REPORT (PROD_REPORT_PRODUCT_ID,PROD_REPORT_MEM_ID,PROD_REPORT_REASON,PROD_REPORT_TIME,PROD_REPORT_STATUS) VALUES (1001,'M000006','違禁品',CURRENT_TIMESTAMP,1);


INSERT INTO PRODUCT_REPORT (PROD_REPORT_PRODUCT_ID,PROD_REPORT_MEM_ID,PROD_REPORT_REASON,PROD_REPORT_TIME,PROD_REPORT_STATUS) VALUES (1008,'M000010','圖文不符',CURRENT_TIMESTAMP,1);


INSERT INTO PRODUCT_REPORT (PROD_REPORT_PRODUCT_ID,PROD_REPORT_MEM_ID,PROD_REPORT_REASON,PROD_REPORT_TIME,PROD_REPORT_STATUS) VALUES (1010,'M000008','圖文不符',CURRENT_TIMESTAMP,1);




--QA_REPORT
DROP SEQUENCE QA_REPORT_SEQ;
CREATE SEQUENCE QA_REPORT_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO QA_REPORT (QUESTION_ID,MEM_ID,QA_STATE) VALUES ('QU000000001','M000001',0);
INSERT INTO QA_REPORT (QUESTION_ID,MEM_ID,QA_STATE) VALUES ('QU000000002','M000002',0);
INSERT INTO QA_REPORT (QUESTION_ID,MEM_ID,QA_STATE) VALUES ('QU000000003','M000003',0);


--MEMBER_REPORT
INSERT INTO MEMBER_REPORT (MEM_ID_REPORT,MEM_ID_REPORTED,REPORT_TIME,REPORT_REASON,MEM_REP_STA)VALUES ('M000001','M000002',TO_TIMESTAMP('18-07-10 08.10.00 ','DD-MM-YY HH.MI.SS'),'看你不爽','1');
INSERT INTO MEMBER_REPORT (MEM_ID_REPORT,MEM_ID_REPORTED,REPORT_TIME,REPORT_REASON,MEM_REP_STA)VALUES ('M000002','M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),'看你長太帥','2');
INSERT INTO MEMBER_REPORT (MEM_ID_REPORT,MEM_ID_REPORTED,REPORT_TIME,REPORT_REASON,MEM_REP_STA)VALUES ('M000003','M000005',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),'看你長太師','1');
INSERT INTO MEMBER_REPORT (MEM_ID_REPORT,MEM_ID_REPORTED,REPORT_TIME,REPORT_REASON,MEM_REP_STA)VALUES ('M000005','M000004',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),'還可以吧','2');
INSERT INTO MEMBER_REPORT (MEM_ID_REPORT,MEM_ID_REPORTED,REPORT_TIME,REPORT_REASON,MEM_REP_STA)VALUES ('M000004','M000002',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),'你是不是想','1');


--PHOTO_WALL
DROP SEQUENCE PHOTO_WALL_SEQ;
CREATE SEQUENCE PHOTO_WALL_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE;


INSERT INTO PHOTO_WALL (PHOTO_NO,MEM_ID,PO_TIME,PHOTO,PHOTO_STA,PHOTO_CONTENT) VALUES ('P'||LPAD(TO_CHAR(PHOTO_WALL_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),bfile_to_blob (BFILENAME ('IMAGE_PHOTO_WALL_DIR','PW0001.jpg')),1,'我在台北天氣晴');
INSERT INTO PHOTO_WALL (PHOTO_NO,MEM_ID,PO_TIME,PHOTO,PHOTO_STA,PHOTO_CONTENT) VALUES ('P'||LPAD(TO_CHAR(PHOTO_WALL_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),bfile_to_blob (BFILENAME ('IMAGE_PHOTO_WALL_DIR','PW0002.jpg')),1,'我在台北天氣晴');
INSERT INTO PHOTO_WALL (PHOTO_NO,MEM_ID,PO_TIME,PHOTO,PHOTO_STA,PHOTO_CONTENT) VALUES ('P'||LPAD(TO_CHAR(PHOTO_WALL_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),bfile_to_blob (BFILENAME ('IMAGE_PHOTO_WALL_DIR','PW0003.jpg')),1,'我在台北天氣晴');
INSERT INTO PHOTO_WALL (PHOTO_NO,MEM_ID,PO_TIME,PHOTO,PHOTO_STA,PHOTO_CONTENT) VALUES ('P'||LPAD(TO_CHAR(PHOTO_WALL_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),bfile_to_blob (BFILENAME ('IMAGE_PHOTO_WALL_DIR','PW0004.jpg')),1,'我在台北天氣晴');
INSERT INTO PHOTO_WALL (PHOTO_NO,MEM_ID,PO_TIME,PHOTO,PHOTO_STA,PHOTO_CONTENT) VALUES ('P'||LPAD(TO_CHAR(PHOTO_WALL_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),bfile_to_blob (BFILENAME ('IMAGE_PHOTO_WALL_DIR','PW0005.jpg')),1,'我在台北天氣晴');
INSERT INTO PHOTO_WALL (PHOTO_NO,MEM_ID,PO_TIME,PHOTO,PHOTO_STA,PHOTO_CONTENT) VALUES ('P'||LPAD(TO_CHAR(PHOTO_WALL_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),bfile_to_blob (BFILENAME ('IMAGE_PHOTO_WALL_DIR','PW0006.jpg')),1,'我在台北天氣晴');
INSERT INTO PHOTO_WALL (PHOTO_NO,MEM_ID,PO_TIME,PHOTO,PHOTO_STA,PHOTO_CONTENT) VALUES ('P'||LPAD(TO_CHAR(PHOTO_WALL_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),bfile_to_blob (BFILENAME ('IMAGE_PHOTO_WALL_DIR','PW0007.jpg')),1,'我在台北天氣晴');
INSERT INTO PHOTO_WALL (PHOTO_NO,MEM_ID,PO_TIME,PHOTO,PHOTO_STA,PHOTO_CONTENT) VALUES ('P'||LPAD(TO_CHAR(PHOTO_WALL_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),bfile_to_blob (BFILENAME ('IMAGE_PHOTO_WALL_DIR','PW0008.jpg')),1,'我在台北天氣晴');
INSERT INTO PHOTO_WALL (PHOTO_NO,MEM_ID,PO_TIME,PHOTO,PHOTO_STA,PHOTO_CONTENT) VALUES ('P'||LPAD(TO_CHAR(PHOTO_WALL_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),bfile_to_blob (BFILENAME ('IMAGE_PHOTO_WALL_DIR','PW0009.jpg')),1,'我在台北天氣晴');
INSERT INTO PHOTO_WALL (PHOTO_NO,MEM_ID,PO_TIME,PHOTO,PHOTO_STA,PHOTO_CONTENT) VALUES ('P'||LPAD(TO_CHAR(PHOTO_WALL_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('18-07-20 08.20.00 ','DD-MM-YY HH.MI.SS'),bfile_to_blob (BFILENAME ('IMAGE_PHOTO_WALL_DIR','PW0010.jpg')),1,'我在台北天氣晴');


--CHATROOM_JOIN




--TRIP 行程
DROP SEQUENCE TRIP_SEQ;
CREATE SEQUENCE TRIP_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO TRIP (TRIP_NO,MEM_ID,TRIP_NAME,TRIP_STARTDAY,TRIP_DAYS,TRIP_VIEWS,TRIP_STATUS) VALUES ('T'||LPAD(TO_CHAR(TRIP_SEQ.NEXTVAL), 9, '0'),'M000001','台灣3天行',TO_DATE('2022-02-22','YYYY-MM-DD'),3,0,1);
INSERT INTO TRIP (TRIP_NO,MEM_ID,TRIP_NAME,TRIP_STARTDAY,TRIP_DAYS,TRIP_VIEWS,TRIP_STATUS) VALUES ('T'||LPAD(TO_CHAR(TRIP_SEQ.NEXTVAL), 9, '0'),'M000003','日月潭1天行',TO_DATE('2019-01-02','YYYY-MM-DD'),1,0,1);
INSERT INTO TRIP (TRIP_NO,MEM_ID,TRIP_NAME,TRIP_STARTDAY,TRIP_DAYS,TRIP_VIEWS,TRIP_STATUS) VALUES ('T'||LPAD(TO_CHAR(TRIP_SEQ.NEXTVAL), 9, '0'),'M000001','盤子2日遊',TO_DATE('2018-08-07','YYYY-MM-DD'),2,0,1);




--TRIP_DAYS 行程天
DROP SEQUENCE TRIPDAYS_SEQ;
CREATE SEQUENCE TRIPDAYS_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO TRIP_DAYS (TRIPDAY_NO,TRIP_NO,TRIPDAY_DAYS,TRIPDAY_DATE,TRIPDAY_HOTELNAME,TRIPDAY_HOTELSTART,TRIPDAY_HOTELNOTE,TRIPDAY_HOTELCOST) VALUES ('TD'||LPAD(TO_CHAR(TRIPDAYS_SEQ.NEXTVAL), 8, '0'),'T000000001',1,TO_DATE('2022-02-22','YYYY-MM-DD'),'町記憶旅店',1320,'108台北市萬華區昆明街119號',2010);
INSERT INTO TRIP_DAYS (TRIPDAY_NO,TRIP_NO,TRIPDAY_DAYS,TRIPDAY_DATE,TRIPDAY_HOTELNAME,TRIPDAY_HOTELSTART,TRIPDAY_HOTELNOTE,TRIPDAY_HOTELCOST) VALUES ('TD'||LPAD(TO_CHAR(TRIPDAYS_SEQ.NEXTVAL), 8, '0'),'T000000001',2,TO_DATE('2022-02-23','YYYY-MM-DD'),'第一站背包客青旅',1290,'22448新北市瑞芳區八號巷24號',1200);
INSERT INTO TRIP_DAYS (TRIPDAY_NO,TRIP_NO,TRIPDAY_DAYS,TRIPDAY_DATE,TRIPDAY_HOTELNAME,TRIPDAY_HOTELSTART,TRIPDAY_HOTELNOTE,TRIPDAY_HOTELCOST) VALUES ('TD'||LPAD(TO_CHAR(TRIPDAYS_SEQ.NEXTVAL), 8, '0'),'T000000001',3,TO_DATE('2022-02-24','YYYY-MM-DD'),NULL,NULL,NULL,NULL);
INSERT INTO TRIP_DAYS (TRIPDAY_NO,TRIP_NO,TRIPDAY_DAYS,TRIPDAY_DATE,TRIPDAY_HOTELNAME,TRIPDAY_HOTELSTART,TRIPDAY_HOTELNOTE,TRIPDAY_HOTELCOST) VALUES ('TD'||LPAD(TO_CHAR(TRIPDAYS_SEQ.NEXTVAL), 8, '0'),'T000000002',1,TO_DATE('2019-01-02','YYYY-MM-DD'),NULL,NULL,NULL,NULL);
INSERT INTO TRIP_DAYS (TRIPDAY_NO,TRIP_NO,TRIPDAY_DAYS,TRIPDAY_DATE,TRIPDAY_HOTELNAME,TRIPDAY_HOTELSTART,TRIPDAY_HOTELNOTE,TRIPDAY_HOTELCOST) VALUES ('TD'||LPAD(TO_CHAR(TRIPDAYS_SEQ.NEXTVAL), 8, '0'),'T000000003',1,TO_DATE('2018-08-07','YYYY-MM-DD'),'AZURE湛藍海岸民宿',1350,'NO.196南灣路恆春鎮屏東縣946',3825);
INSERT INTO TRIP_DAYS (TRIPDAY_NO,TRIP_NO,TRIPDAY_DAYS,TRIPDAY_DATE,TRIPDAY_HOTELNAME,TRIPDAY_HOTELSTART,TRIPDAY_HOTELNOTE,TRIPDAY_HOTELCOST) VALUES ('TD'||LPAD(TO_CHAR(TRIPDAYS_SEQ.NEXTVAL), 8, '0'),'T000000003',2,TO_DATE('2018-08-08','YYYY-MM-DD'),NULL,NULL,NULL,NULL);
--ORD
--訂單
DROP SEQUENCE ORD_SEQ;
CREATE SEQUENCE ORD_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;








INSERT INTO ORD (ORDER_ID,BUYER_MEM_ID,SELLER_MEM_ID,ORDER_ADDRESS,PAYMENT_STATUS,PAYMENT_METHOD,SHIPMENT_STATUS,ORDER_DATE,ORDER_STATUS,ORDER_TOTAL,ORDER_ITEM,SHIPMENT_METHOD,ORD_STORE_711_NAME) VALUES (TO_CHAR(SYSDATE,'YYYYMMDD')||'-'||LPAD(TO_CHAR(ORD_SEQ.NEXTVAL), 6, '0'),'M000009','M000002','台北市中正區汀州路二段210號',1,2,1,CURRENT_TIMESTAMP,1,690,3,2,'古亭');


INSERT INTO ORD (ORDER_ID,BUYER_MEM_ID,SELLER_MEM_ID,ORDER_ADDRESS,PAYMENT_STATUS,PAYMENT_METHOD,SHIPMENT_STATUS,ORDER_DATE,ORDER_STATUS,ORDER_TOTAL,ORDER_ITEM,STOB_RATING,STOB_RATING_DESCR,BTOS_RATING,BTOS_RATING_DESCR,SHIPMENT_ID,SHIPMENT_METHOD,ORD_STORE_711_NAME) VALUES (TO_CHAR(SYSDATE,'YYYYMMDD')||'-'||LPAD(TO_CHAR(ORD_SEQ.NEXTVAL), 6, '0'),'M000010','M000009','台北市大安區東豐街43號45號1樓',2,1,3,TO_TIMESTAMP('08-07-18 08.21.19 ', 'DD-MM-YY HH.MI.SS '),4,500,1,5,'好買家~~',5,'貼心好賣家~~','E26220241204',2,'敦維');


INSERT INTO ORD (ORDER_ID,BUYER_MEM_ID,SELLER_MEM_ID,ORDER_ADDRESS,PAYMENT_STATUS,PAYMENT_METHOD,SHIPMENT_STATUS,ORDER_DATE,ORDER_STATUS,ORDER_TOTAL,ORDER_ITEM,STOB_RATING,STOB_RATING_DESCR,BTOS_RATING,BTOS_RATING_DESCR,SHIPMENT_ID,SHIPMENT_METHOD,ORD_STORE_711_NAME) VALUES (TO_CHAR(SYSDATE,'YYYYMMDD')||'-'||LPAD(TO_CHAR(ORD_SEQ.NEXTVAL), 6, '0'),'M000003','M000004','台北市大安區信義路四段74號1樓',2,1,3,TO_TIMESTAMP('01-07-18 08.21.19 ', 'DD-MM-YY HH.MI.SS '),4,2290,1,5,'取件給評都快速的好買家',5,'出貨快速~商品好!好賣家~~','C88808407942',2,'安信');


--ORDER_DETAILS
--購買清單
DROP TABLE ORDER_DETAILS CASCADE CONSTRAINTS;
CREATE TABLE ORDER_DETAILS (
 DETAILS_ORDER_ID VARCHAR2(15) NOT NULL, 
 DETAILS_PRODUCT_ID NUMBER(10,0)  NOT NULL,
 DETAILS_ORDER_QTY NUMBER(10,0)  NOT NULL,
 DETAILS_ORDER_TOTAL NUMBER(10,0)  NOT NULL
);


ALTER TABLE ORDER_DETAILS ADD CONSTRAINT PK_ORDER_DETAILS PRIMARY KEY (DETAILS_ORDER_ID,DETAILS_PRODUCT_ID);


INSERT INTO ORDER_DETAILS (DETAILS_ORDER_ID, DETAILS_PRODUCT_ID,DETAILS_ORDER_QTY,DETAILS_ORDER_TOTAL) VALUES (TO_CHAR(SYSDATE,'YYYYMMDD')||'-'||LPAD(TO_CHAR(ORD_SEQ.CURRVAL), 6, '0')
,1001,1,200);


INSERT INTO ORDER_DETAILS (DETAILS_ORDER_ID, DETAILS_PRODUCT_ID,DETAILS_ORDER_QTY,DETAILS_ORDER_TOTAL) VALUES (TO_CHAR(SYSDATE,'YYYYMMDD')||'-'||LPAD(TO_CHAR(ORD_SEQ.CURRVAL), 6, '0')
,1002,1,490);


INSERT INTO ORDER_DETAILS (DETAILS_ORDER_ID, DETAILS_PRODUCT_ID,DETAILS_ORDER_QTY,DETAILS_ORDER_TOTAL) VALUES (TO_CHAR(SYSDATE,'YYYYMMDD')||'-'||LPAD(TO_CHAR(ORD_SEQ.CURRVAL), 6, '0')
,1003,1,1600);


--NOTICE
DROP SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO NOTICE (NOTICE_ID,MEM_ID) VALUES ('NT'||LPAD(TO_CHAR(QA_REPORT_SEQ.NEXTVAL), 9, '0'),'M000001');
INSERT INTO NOTICE (NOTICE_ID,MEM_ID) VALUES ('NT'||LPAD(TO_CHAR(QA_REPORT_SEQ.NEXTVAL), 9, '0'),'M000002');
INSERT INTO NOTICE (NOTICE_ID,MEM_ID) VALUES ('NT'||LPAD(TO_CHAR(QA_REPORT_SEQ.NEXTVAL), 9, '0'),'M000003');






--TRAFFIC_TRIP 交通行程
DROP SEQUENCE TRATRIP_SEQ;
CREATE SEQUENCE TRATRIP_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
INSERT INTO TRAFFIC_TRIP (TRATRIP_NO,TRIPDAY_NO,TRATRIP_TYPE,TRATRIP_COST,TRATRIP_START,TRATRIP_END,TRIP_ORDER,TRATRIP_NAME,TRATRIP_NOTE) VALUES ('TT'||LPAD(TO_CHAR(TRATRIP_SEQ.NEXTVAL), 8, '0'),'TD00000001',0,35,1080,1100,2,'MTR','西門站至松山站');
INSERT INTO TRAFFIC_TRIP (TRATRIP_NO,TRIPDAY_NO,TRATRIP_TYPE,TRATRIP_COST,TRATRIP_START,TRATRIP_END,TRIP_ORDER,TRATRIP_NAME,TRATRIP_NOTE) VALUES ('TT'||LPAD(TO_CHAR(TRATRIP_SEQ.NEXTVAL), 8, '0'),'TD00000002',3,100,510,630,1,'1062公車','忠孝復興至九份老街');
INSERT INTO TRAFFIC_TRIP (TRATRIP_NO,TRIPDAY_NO,TRATRIP_TYPE,TRATRIP_COST,TRATRIP_START,TRATRIP_END,TRIP_ORDER,TRATRIP_NAME,TRATRIP_NOTE) VALUES ('TT'||LPAD(TO_CHAR(TRATRIP_SEQ.NEXTVAL), 8, '0'),'TD00000003',3,100,540,660,1,'1062公車','九份至松山車站');




--QA_CLASSIFICATION
DROP SEQUENCE QA_CLASSIFICATION_SEQ;
CREATE SEQUENCE QA_CLASSIFICATION_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO QA_CLASSIFICATION (LIST_ID,QUESTION_ID) VALUES ('LI000000001','QU000000001');


INSERT INTO QA_CLASSIFICATION (LIST_ID,QUESTION_ID) VALUES ('LI000000002','QU000000002');


INSERT INTO QA_CLASSIFICATION (LIST_ID,QUESTION_ID) VALUES ('LI000000003','QU000000003');


--GRP
DROP SEQUENCE GRP_SEQ;
CREATE SEQUENCE GRP_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE;


INSERT INTO GRP (GRP_ID,MEM_ID,GRP_START,GRP_END,GRP_CNT,GRP_ACPT,TRIP_NO,TRIP_START,TRIP_END,TRIP_LOCALE,TRIP_DETAILS,GRP_PHOTO,GRP_STATUS,CHATROOM_ID) 
VALUES ('GRP'||LPAD(TO_CHAR(GRP_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('17-07-18 08.20.00 ','DD-MM-YY HH.MI.SS'),TO_TIMESTAMP('18-07-18 08.00.00 ','DD-MM-YY HH.MI.SS'),'3','3','T000000001',TO_TIMESTAMP('03-08-18 09.30.00 ','DD-MM-YY HH.MI.SS'),TO_TIMESTAMP('10-08-18 09.30.00 ','DD-MM-YY HH.MI.SS'),'台灣','台灣難波萬,台灣讚讚讚',bfile_to_blob (BFILENAME ('IMAGE_GRP_DIR','GRP_001.jpg')),'2','CR000001');


INSERT INTO GRP (GRP_ID,MEM_ID,GRP_START,GRP_END,GRP_CNT,GRP_ACPT,TRIP_NO,TRIP_START,TRIP_END,TRIP_LOCALE,TRIP_DETAILS,GRP_PHOTO,GRP_STATUS,CHATROOM_ID) 
VALUES ('GRP'||LPAD(TO_CHAR(GRP_SEQ.NEXTVAL), 6, '0'),'M000001',TO_TIMESTAMP('17-07-18 08.20.00 ','DD-MM-YY HH.MI.SS'),TO_TIMESTAMP('18-07-18 08.00.00 ','DD-MM-YY HH.MI.SS'),'3','3','T000000001',TO_TIMESTAMP('03-08-18 09.30.00 ','DD-MM-YY HH.MI.SS'),TO_TIMESTAMP('10-08-18 09.30.00 ','DD-MM-YY HH.MI.SS'),'台灣','台灣難波萬,台灣讚讚讚',bfile_to_blob (BFILENAME ('IMAGE_GRP_DIR','GRP_001.jpg')),'2','CR000001');


INSERT INTO GRP (GRP_ID,MEM_ID,GRP_START,GRP_END,GRP_CNT,GRP_ACPT,TRIP_NO,TRIP_START,TRIP_END,TRIP_LOCALE,TRIP_DETAILS,GRP_PHOTO,GRP_STATUS,CHATROOM_ID) 
VALUES ('GRP'||LPAD(TO_CHAR(GRP_SEQ.NEXTVAL), 6, '0'),'M000003',TO_TIMESTAMP('15-11-18 08.15.00 ','DD-MM-YY HH.MI.SS'),TO_TIMESTAMP('17-11-18 10.00.00 ','DD-MM-YY HH.MI.SS'),'4','3','T000000001',TO_TIMESTAMP('03-08-18 09.30.00 ','DD-MM-YY HH.MI.SS'),TO_TIMESTAMP('10-08-18 09.30.00 ','DD-MM-YY HH.MI.SS'),'紐約','讚讚讚',bfile_to_blob (BFILENAME ('IMAGE_GRP_DIR','GRP_001.jpg')),'1','CR000003');


INSERT INTO GRP (GRP_ID,MEM_ID,GRP_START,GRP_END,GRP_CNT,GRP_ACPT,TRIP_NO,TRIP_START,TRIP_END,TRIP_LOCALE,TRIP_DETAILS,GRP_PHOTO,GRP_STATUS,CHATROOM_ID) 
VALUES ('GRP'||LPAD(TO_CHAR(GRP_SEQ.NEXTVAL), 6, '0'),'M000004',TO_TIMESTAMP('02-12-18 12.00.00 ','DD-MM-YY HH.MI.SS'),TO_TIMESTAMP('05-12-18 11.30.00 ','DD-MM-YY HH.MI.SS'),'5','5','T000000003',TO_TIMESTAMP('03-08-18 09.30.00 ','DD-MM-YY HH.MI.SS'),TO_TIMESTAMP('10-08-18 09.30.00 ','DD-MM-YY HH.MI.SS'),'巴黎','讚讚讚',bfile_to_blob (BFILENAME ('IMAGE_GRP_DIR','GRP_001.jpg')),'2','CR000001');


INSERT INTO GRP (GRP_ID,MEM_ID,GRP_START,GRP_END,GRP_CNT,GRP_ACPT,TRIP_NO,TRIP_START,TRIP_END,TRIP_LOCALE,TRIP_DETAILS,GRP_PHOTO,GRP_STATUS,CHATROOM_ID) 
VALUES ('GRP'||LPAD(TO_CHAR(GRP_SEQ.NEXTVAL), 6, '0'),'M000005',TO_TIMESTAMP('24-01-18 01.20.00 ','DD-MM-YY HH.MI.SS'),TO_TIMESTAMP('26-01-18 03.00.00 ','DD-MM-YY HH.MI.SS'),'1','0','T000000002',TO_TIMESTAMP('03-08-18 09.30.00 ','DD-MM-YY HH.MI.SS'),TO_TIMESTAMP('10-08-18 09.30.00 ','DD-MM-YY HH.MI.SS'),'大陸','我覺得可以',bfile_to_blob (BFILENAME ('IMAGE_GRP_DIR','GRP_001.jpg')),'3','CR000002');


--GRP_MEM
INSERT INTO GRP_MEM (GRP_ID,MEM_ID,GRP_LEADER) VALUES ('GRP000001','M000001','1');
INSERT INTO GRP_MEM (GRP_ID,MEM_ID,GRP_LEADER) VALUES ('GRP000002','M000002','0');
INSERT INTO GRP_MEM (GRP_ID,MEM_ID,GRP_LEADER) VALUES ('GRP000003','M000003','1');
INSERT INTO GRP_MEM (GRP_ID,MEM_ID,GRP_LEADER) VALUES ('GRP000004','M000004','0');
INSERT INTO GRP_MEM (GRP_ID,MEM_ID,GRP_LEADER) VALUES ('GRP000005','M000005','1');
--GRP_COM
DROP SEQUENCE GRP_COM_SEQ;
CREATE SEQUENCE GRP_COM_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE;


INSERT INTO GRP_COM (GRP_COM_ID,GRP_ID,MEM_ID,GRP_COM) 
VALUES (LPAD(TO_CHAR(GRP_COM_SEQ.NEXTVAL), 6, '0'),'GRP000001','M000001','揪團買COCO');
INSERT INTO GRP_COM (GRP_COM_ID,GRP_ID,MEM_ID,GRP_COM)
VALUES (LPAD(TO_CHAR(GRP_COM_SEQ.NEXTVAL), 6, '0'),'GRP000002','M000002','揪團買COCO');
INSERT INTO GRP_COM (GRP_COM_ID,GRP_ID,MEM_ID,GRP_COM)
VALUES (LPAD(TO_CHAR(GRP_COM_SEQ.NEXTVAL), 6, '0'),'GRP000003','M000003','揪團買COCO');
INSERT INTO GRP_COM (GRP_COM_ID,GRP_ID,MEM_ID,GRP_COM)
VALUES (LPAD(TO_CHAR(GRP_COM_SEQ.NEXTVAL), 6, '0'),'GRP000004','M000004','揪團買COCO');
INSERT INTO GRP_COM (GRP_COM_ID,GRP_ID,MEM_ID,GRP_COM)
VALUES (LPAD(TO_CHAR(GRP_COM_SEQ.NEXTVAL), 6, '0'),'GRP000005','M000005','揪團買COCO');




--TRIP_COLLECT 行程收藏


INSERT INTO TRIP_COLLECT (TRIP_NO,MEM_ID) VALUES ('T000000001','M000002');
INSERT INTO TRIP_COLLECT (TRIP_NO,MEM_ID) VALUES ('T000000001','M000004');
INSERT INTO TRIP_COLLECT (TRIP_NO,MEM_ID) VALUES ('T000000003','M000005');




--BLOG
SET SCAN OFF;
DROP SEQUENCE BLOG_SEQ;
CREATE SEQUENCE BLOG_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
INSERT INTO BLOG (BLOG_ID,TRIP_NO,MEM_ID,BLOG_DATE,BLOG_TITLE,BLOG_CONTENT,TRAVEL_DATE,BLOG_VIEWS,BLOG_STATUS,BLOG_COVERIMAGE) 
VALUES(TO_CHAR('B'||LPAD(TO_CHAR(BLOG_SEQ.NEXTVAL), 6, '0')),
'T000000001',
'M000001',
TO_TIMESTAMP('2018-07-08 08:20:30','YYYY-MM-DD HH24:MI:SS'),
'我是標題',
'<H1>WIKI</H1>


                    <P>維基百科，自由的百科全書</P>


                    <P><A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/WIKI#MW-HEAD">跳至導覽</A><A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/WIKI#P-SEARCH">跳至搜尋</A></P>',
TO_DATE('2018-07-08','YYYY-MM-DD'),
1,
0,
bfile_to_blob (BFILENAME ('IMAGE_BLOG_DIR','blog001.jpg'))
);
INSERT INTO BLOG (BLOG_ID,TRIP_NO,MEM_ID,BLOG_DATE,BLOG_TITLE,BLOG_CONTENT,TRAVEL_DATE,BLOG_VIEWS,BLOG_STATUS,BLOG_COVERIMAGE) 
VALUES(TO_CHAR('B'||LPAD(TO_CHAR(BLOG_SEQ.NEXTVAL), 6, '0')),
'T000000002',
'M000002',
TO_TIMESTAMP('2018-07-08 08:20:30','YYYY-MM-DD HH24:MI:SS'),
'我是標題',
'<H2>歷史</H2>


<P><A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/FILE:WIKIWIKI.JPG"><IMG ALT="" BORDER="0" HSPACE="0" SRC="HTTPS://UPLOAD.WIKIMEDIA.ORG/WIKIPEDIA/COMMONS/THUMB/B/B6/WIKIWIKI.JPG/250PX-WIKIWIKI.JPG" STYLE="BORDER:0PX SOLID BLACK; FLOAT:RIGHT; HEIGHT:263PX; MARGIN-BOTTOM:0PX; MARGIN-LEFT:0PX; MARGIN-RIGHT:0PX; MARGIN-TOP:0PX; WIDTH:250PX" VSPACE="0" /></A></P>


<P><A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E6%AA%80%E9%A6%99%E5%B1%B1">檀香山</A>的WIKI WIKI站牌</P>


<P>WIKI軟體由<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E8%BD%AF%E4%BB%B6%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F">軟體設計模式</A>社群開發，用來書寫與討論模式語言。<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E6%B2%83%E5%BE%B7%C2%B7%E5%9D%8E%E5%AE%81%E5%AE%89">沃德&MIDDOT;坎寧安</A>於1995年3月25日成立了第一個WIKI網站：<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/W/INDEX.PHP?TITLE=WIKIWIKIWEB&AMP;ACTION=EDIT&AMP;REDLINK=1">WIKIWIKIWEB</A>，用來補充他自己經營的軟體設計模式網站。他發明了WIKI這個名字以及相關概念，並且實作了第一個<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/WIKI%E5%BC%95%E6%93%8E">WIKI引擎</A>。坎寧安說自己是根據<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E6%AA%80%E9%A6%99%E5%B1%B1">檀香山</A>的WEEKEE WEEKEE（意為「快點快點」）公車取名的。這是他到檀香山學會的第一個<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E5%A4%8F%E5%A8%81%E5%A4%B7%E8%AF%AD">夏威夷語</A>句子。</P>


<P>坎寧安說，WIKI的構想來自他自己在1980年代晚期利用<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E8%98%8B%E6%9E%9C%E9%9B%BB%E8%85%A6">蘋果電腦</A><A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/HYPERCARD">HYPERCARD</A>程式作出的一個小功能<SUP><A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/WIKI#CITE_NOTE-4">[4]</A></SUP>。HYPERCARD類似<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E5%90%8D%E7%89%87">名片</A>整理程式，可用來紀錄人物與相關事物。HYPERCARD管理許多稱為「卡片」的資料，每張卡片上都可劃分欄位、加上圖片、有樣式的文字或按鈕等等，而且這些內容都可在查閱卡片的同時修改編輯。HYPERCARD類似於後來的網頁，但是缺乏一些重要特徵。</P>


<P>坎寧安認為原來的HYPERCARD程式十分有用，但創造卡片與卡片之間的連結卻很困難。於是他不用HYPERCARD程式原本的創造連結功能，而改用「隨選搜尋」的方式自己增添了一個新的連結功能。使用者只要將連結輸入卡片上的一個特殊欄位，而這個欄位每一行都有一個按鈕。按下按鈕時如果卡片已經存在，按鈕就會帶使用者去那張卡片，否則就發出嗶聲，而繼續壓著按鈕不放，程式就會為使用者產生一張卡片。</P>


<P>坎寧安向他的朋友展示了這個程式和他自己寫的人事卡片，往往會有人指出卡片之中的內容不太對，他們就可當場利用HYPERCARD初始的功能修正內容，並利用坎寧安加入的新功能補充連結。</P>


<P>坎寧安後來在別處又寫了這樣的功能，而且這次他還增加了多使用者寫作功能。新功能之一是程式會在每一次任何一張卡片被更改時，自動在「最近更改」卡片上增加一個連往被更改卡片的連結。坎寧安自己常常看「最近更改」卡片，而且還會注意到空白的說明欄位會讓他想要描述一下更改的摘要<SUP><A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/WIKI#CITE_NOTE-5">[5]</A></SUP>。</P>',
TO_DATE('2018-07-08','YYYY-MM-DD'),
1,
0,
bfile_to_blob (BFILENAME ('IMAGE_BLOG_DIR','blog002.jpg'))
);
INSERT INTO BLOG (BLOG_ID,TRIP_NO,MEM_ID,BLOG_DATE,BLOG_TITLE,BLOG_CONTENT,TRAVEL_DATE,BLOG_VIEWS,BLOG_STATUS,BLOG_COVERIMAGE) 
VALUES(TO_CHAR('B'||LPAD(TO_CHAR(BLOG_SEQ.NEXTVAL), 6, '0')),
'T000000003',
'M000003',
TO_TIMESTAMP('2018-07-08 08:20:30','YYYY-MM-DD HH24:MI:SS'),
'我是標題',
'<H3>編輯WIKI頁面</H3>


<P>WIKI中用戶使用很多方式來編輯。通常需要通過文字標記式語言。</P>


<H2>應用</H2>


<P><A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/FILE:HNL_WIKI_WIKI_BUS.JPG"><IMG ALT="" BORDER="0" HSPACE="0" SRC="HTTPS://UPLOAD.WIKIMEDIA.ORG/WIKIPEDIA/COMMONS/THUMB/4/42/HNL_WIKI_WIKI_BUS.JPG/300PX-HNL_WIKI_WIKI_BUS.JPG" STYLE="BORDER:0PX SOLID BLACK; FLOAT:RIGHT; HEIGHT:226PX; MARGIN-BOTTOM:0PX; MARGIN-LEFT:0PX; MARGIN-RIGHT:0PX; MARGIN-TOP:0PX; WIDTH:300PX" VSPACE="0" /></A></P>


<P>WIKI-WIKI<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E5%B7%B4%E5%A3%AB">巴士</A></P>


<P>WIKI在一些需要<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E5%86%85%E5%AE%B9%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F">內容管理系統</A>的企業中得到了廣泛應用<SUP><A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/WIKI#CITE_NOTE-6">[6]</A></SUP>、<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/JOTSPOT">JOTSPOT</A>和<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/W/INDEX.PHP?TITLE=SOCIALTEXT&AMP;ACTION=EDIT&AMP;REDLINK=1">SOCIALTEXT</A>是創WIKI企業應用的先河。WIKI可以在高校教育環境中發揮積極的作用，但是直到2006年，WIKI應用於教育的案例在全球都比較少。WIKI除了被用來建立網站外，也被用作編寫<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E7%B6%B2%E8%AA%8C">部落格</A>。WIKI在中小學教育方面，可以作為學生協助學習的平台。</P>


<H2>實施</H2>


<P>WIKI軟體是一款執行WIKI的<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E7%BE%A4%E4%BB%B6">群件</A>，允許使用常見的WEB瀏覽器建立和修改網頁，被作為<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E6%87%89%E7%94%A8%E7%A8%8B%E5%BC%8F%E4%BC%BA%E6%9C%8D%E5%99%A8">應用程式伺服器</A>在多個<A HREF="HTTPS://ZH.WIKIPEDIA.ORG/WIKI/%E7%BD%91%E9%A1%B5%E6%9C%8D%E5%8A%A1%E5%99%A8">網頁伺服器</A>上運作。</P>


<H2>導航</H2>


<P>在大多數頁面的文字，通常有大量的超文字連結到其他網頁。大多數WIKI有一個反向的功能，它顯示所有連結到一個給定頁面的頁面。</P>',
TO_DATE('2018-07-08','YYYY-MM-DD'),
1,
0,
bfile_to_blob (BFILENAME ('IMAGE_BLOG_DIR','blog003.jpg'))
);


--BLOG_COLLECT
INSERT INTO BLOG_COLLECT (BLOG_ID,MEM_ID) VALUES('B000001','M000001');
INSERT INTO BLOG_COLLECT (BLOG_ID,MEM_ID) VALUES('B000002','M000002');
INSERT INTO BLOG_COLLECT (BLOG_ID,MEM_ID) VALUES('B000003','M000003');
INSERT INTO BLOG_COLLECT (BLOG_ID,MEM_ID) VALUES('B000001','M000002');
INSERT INTO BLOG_COLLECT (BLOG_ID,MEM_ID) VALUES('B000001','M000003');
--BLOG_TAG
INSERT INTO BLOG_TAG (BLOG_ID,BTN_ID) 
VALUES('B000001','BT000001');
INSERT INTO BLOG_TAG (BLOG_ID,BTN_ID) 
VALUES('B000002','BT000002');
INSERT INTO BLOG_TAG (BLOG_ID,BTN_ID) 
VALUES('B000003','BT000003');
INSERT INTO BLOG_TAG (BLOG_ID,BTN_ID) 
VALUES('B000001','BT000002');
INSERT INTO BLOG_TAG (BLOG_ID,BTN_ID) 
VALUES('B000001','BT000003');
--BLOG_REPORT
INSERT INTO BLOG_REPORT (BLOG_ID,MEM_ID,BR_STATUS) 
VALUES('B000001','M000001',0);
INSERT INTO BLOG_REPORT (BLOG_ID,MEM_ID,BR_STATUS) 
VALUES('B000002','M000002',0);
INSERT INTO BLOG_REPORT (BLOG_ID,MEM_ID,BR_STATUS) 
VALUES('B000003','M000003',0);
--BLOG_MESSAGE
DROP SEQUENCE BM_SEQ;
CREATE SEQUENCE BM_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO BLOG_MESSAGE (MESSAGE_ID,BLOG_ID,MEM_ID,BLOG_MESSAGE,BM_STATUS) 
VALUES ('BM'||LPAD(TO_CHAR(BM_SEQ.NEXTVAL), 6, '0'),'B000002','M000001','這篇文章好像葉配',0);
INSERT INTO BLOG_MESSAGE (MESSAGE_ID,BLOG_ID,MEM_ID,BLOG_MESSAGE,BM_STATUS) 
VALUES ('BM'||LPAD(TO_CHAR(BM_SEQ.NEXTVAL), 6, '0'),'B000001','M000002','感覺很好玩，謝謝分享。',0);
INSERT INTO BLOG_MESSAGE (MESSAGE_ID,BLOG_ID,MEM_ID,BLOG_MESSAGE,BM_STATUS) 
VALUES ('BM'||LPAD(TO_CHAR(BM_SEQ.NEXTVAL), 6, '0'),'B000002','M000003','葉配+1',0);
INSERT INTO BLOG_MESSAGE (MESSAGE_ID,BLOG_ID,MEM_ID,BLOG_MESSAGE,BM_STATUS) 
VALUES ('BM'||LPAD(TO_CHAR(BM_SEQ.NEXTVAL), 6, '0'),'B000003','M000005','謝謝分分分分分分分分分享',0);
INSERT INTO BLOG_MESSAGE (MESSAGE_ID,BLOG_ID,MEM_ID,BLOG_MESSAGE,BM_STATUS) 
VALUES ('BM'||LPAD(TO_CHAR(BM_SEQ.NEXTVAL), 6, '0'),'B000003','M000007','帥帥帥帥帥帥帥帥帥',0);
--BLOG_MESSAGE_REPORT
INSERT INTO BLOG_MESSAGE_REPORT (MESSAGE_ID,MEM_ID,BMR_STATUS) 
VALUES('BM000001','M000001',0);
INSERT INTO BLOG_MESSAGE_REPORT (MESSAGE_ID,MEM_ID,BMR_STATUS) 
VALUES('BM000001','M000002',0);
INSERT INTO BLOG_MESSAGE_REPORT (MESSAGE_ID,MEM_ID,BMR_STATUS) 
VALUES('BM000002','M000003',0);
--ATTRACTIONS_TRIP 景點行程
DROP SEQUENCE ATTTRIP_SEQ;
CREATE SEQUENCE ATTTRIP_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO ATTRACTIONS_TRIP (ATTTRIP_NO,ATT_NO,TRIPDAY_NO,ATTTRIP_COST,ATTTRIP_START,ATTTRIP_END,TRIP_ORDER,ATTTRIP_NOTE) VALUES ('AT'||LPAD(TO_CHAR(ATTTRIP_SEQ.NEXTVAL), 8, '0'),'A000000001','TD00000001',800,780,1080,1,'逛街');
INSERT INTO ATTRACTIONS_TRIP (ATTTRIP_NO,ATT_NO,TRIPDAY_NO,ATTTRIP_COST,ATTTRIP_START,ATTTRIP_END,TRIP_ORDER,ATTTRIP_NOTE) VALUES ('AT'||LPAD(TO_CHAR(ATTTRIP_SEQ.NEXTVAL), 8, '0'),'A000000002','TD00000001',500,630,1290,2,'還是逛街');
INSERT INTO ATTRACTIONS_TRIP (ATTTRIP_NO,ATT_NO,TRIPDAY_NO,ATTTRIP_COST,ATTTRIP_START,ATTTRIP_END,TRIP_ORDER,ATTTRIP_NOTE) VALUES ('AT'||LPAD(TO_CHAR(ATTTRIP_SEQ.NEXTVAL), 8, '0'),'A000000003','TD00000001',600,1080,1260,2,'逛夜市');
--ATTRACTIONS_EDIT 景點共同編輯待審核
DROP SEQUENCE ATTEDIT_SEQ;
CREATE SEQUENCE ATTEDIT_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE	
NOCYCLE
NOCACHE;

Insert into ATTRACTIONS_EDIT (ATTEDIT_NO,MEM_ID,ATTEDIT_DATE,ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS) values ('AE'||LPAD(to_char(ATTEDIT_SEQ.NEXTVAL), 8, '0'),'M000005',sysdate,'A000000002','九份老街',25.107854,121.836218,'台灣','九份老街主要範圍以聚集在基山街、豎崎路及輕便路等街道為主，是全台灣最熱門的觀光景點之一，全年觀光客絡繹不絕。若以客源分析，平日以來自日本、韓國等地的外籍觀光客以及中國大陸、香港、澳門的遊客和本國遊客各占一半，假日則以國民旅遊為主，是北台灣國際級的觀光景點。商圈定位鮮明，集歷史、天然景致、美食文化於一爐。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000002.jpg')),'新北市瑞芳區九份');
Insert into ATTRACTIONS_EDIT (ATTEDIT_NO,MEM_ID,ATTEDIT_DATE,ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS) values ('AE'||LPAD(to_char(ATTEDIT_SEQ.NEXTVAL), 8, '0'),'M000006',sysdate,'A000000006','太魯閣國家公園',24.193926,121.488774,'台灣','太魯閣國家公園是台灣第四座成立的國家公園，前身為日治時期成立之次高太魯閣國立公園（1937-1945）。第二次世界大戰後為國家級風景區，1986年11月12日公告計畫，1986年11月28日成立管理處。位於台灣東部，地跨花蓮縣、臺中市、南投縣三個行政區。園內有台灣第一條東西橫貫公路通過，稱為中橫公路系統。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000006.jpg')),'花蓮縣秀林鄉富世村富世291號');
Insert into ATTRACTIONS_EDIT (ATTEDIT_NO,MEM_ID,ATTEDIT_DATE,ATT_NO,ATT_NAME,ATT_LAT,ATT_LON,COUNTRY,ATT_INFORMATION,ATT_PICTURE,ATT_ADDRESS) values ('AE'||LPAD(to_char(ATTEDIT_SEQ.NEXTVAL), 8, '0'),'M000004',sysdate,'A000000005','清境農場',24.055347,121.157641,'台灣','清境農場位於台灣南投縣仁愛鄉，海拔約1700至2000公尺，為中華民國國軍退除役官兵輔導委員會所經營之公有事業。與武陵農場、梨山福壽山農場合稱為台灣三大高山農場。場址位於南投縣仁愛鄉大同村仁和路170號（台14甲線旁），清境農場地區飲食文化以滇緬料理聞名。',bfile_to_blob (BFILENAME ('IMAGE_ATTRACTIONS_DIR','A000000005.jpg')),'546南投縣仁愛鄉仁和路170號');



--GRP_REPORT
INSERT INTO GRP_REPORT (GRP_ID,MEM_ID,REPORT_REASON,REPORT_TIME,GRP_REP_STA)VALUES ('GRP000001','M000002','看你不爽',TO_TIMESTAMP('15-10-18 08.15.00 ','DD-MM-YY HH.MI.SS'),'1');
INSERT INTO GRP_REPORT (GRP_ID,MEM_ID,REPORT_REASON,REPORT_TIME,GRP_REP_STA)VALUES ('GRP000002','M000004','根本是去喝_的啊',TO_TIMESTAMP('16-11-18 09.15.00 ','DD-MM-YY HH.MI.SS'),'2');
INSERT INTO GRP_REPORT (GRP_ID,MEM_ID,REPORT_REASON,REPORT_TIME,GRP_REP_STA)VALUES ('GRP000003','M000006','帶有不雅廣告',TO_TIMESTAMP('17-11-18 10.15.00 ','DD-MM-YY HH.MI.SS'),'1');
INSERT INTO GRP_REPORT (GRP_ID,MEM_ID,REPORT_REASON,REPORT_TIME,GRP_REP_STA)VALUES ('GRP000004','M000005','揪團變團購',TO_TIMESTAMP('18-04-18 11.15.00 ','DD-MM-YY HH.MI.SS'),'1');
INSERT INTO GRP_REPORT (GRP_ID,MEM_ID,REPORT_REASON,REPORT_TIME,GRP_REP_STA)VALUES ('GRP000005','M000003','主揪的不是妹子',TO_TIMESTAMP('19-06-18 7.15.00 ','DD-MM-YY HH.MI.SS'),'1');
--PHOTO_REPORT
INSERT INTO PHOTO_REPORT (PHOTO_NO,MEM_ID,REPORT_REASON,REPORT_TIME,PHO_REP_STATS) VALUES ('P000001','M000001','照片太可愛',TO_TIMESTAMP('18-08-08 08.08.08 ','DD-MM-YY HH.MI.SS'),'2');
INSERT INTO PHOTO_REPORT (PHOTO_NO,MEM_ID,REPORT_REASON,REPORT_TIME,PHO_REP_STATS) VALUES ('P000008','M000010','照片太閃',TO_TIMESTAMP('18-12-15 08.20.00 ','DD-MM-YY HH.MI.SS'),'1');
INSERT INTO PHOTO_REPORT (PHOTO_NO,MEM_ID,REPORT_REASON,REPORT_TIME,PHO_REP_STATS) VALUES ('P000004','M000003','照片太香',TO_TIMESTAMP('17-10-20 08.20.00 ','DD-MM-YY HH.MI.SS'),'2');
INSERT INTO PHOTO_REPORT (PHOTO_NO,MEM_ID,REPORT_REASON,REPORT_TIME,PHO_REP_STATS) VALUES ('P000006','M000003','照片太帥',TO_TIMESTAMP('17-11-11 08.20.00 ','DD-MM-YY HH.MI.SS'),'1');
INSERT INTO PHOTO_REPORT (PHOTO_NO,MEM_ID,REPORT_REASON,REPORT_TIME,PHO_REP_STATS) VALUES ('P000007','M000007','照片太美',TO_TIMESTAMP('18-12-12 08.20.00 ','DD-MM-YY HH.MI.SS'),'2');
--PHOTO_TAG_LIST


INSERT INTO PHOTO_TAG_LIST (PHOTO_TAG_NO,PHOTO_NO) VALUES ('PTN000001','P000001');
INSERT INTO PHOTO_TAG_LIST (PHOTO_TAG_NO,PHOTO_NO) VALUES ('PTN000002','P000002');
INSERT INTO PHOTO_TAG_LIST (PHOTO_TAG_NO,PHOTO_NO) VALUES ('PTN000003','P000003');
INSERT INTO PHOTO_TAG_LIST (PHOTO_TAG_NO,PHOTO_NO) VALUES ('PTN000004','P000004');
INSERT INTO PHOTO_TAG_LIST (PHOTO_TAG_NO,PHOTO_NO) VALUES ('PTN000005','P000005');


COMMIT;